// Generated by gencpp from file delphi_srr_msgs/SrrStatus1.msg
// DO NOT EDIT!


#ifndef DELPHI_SRR_MSGS_MESSAGE_SRRSTATUS1_H
#define DELPHI_SRR_MSGS_MESSAGE_SRRSTATUS1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_srr_msgs
{
template <class ContainerAllocator>
struct SrrStatus1_
{
  typedef SrrStatus1_<ContainerAllocator> Type;

  SrrStatus1_()
    : header()
    , CAN_TX_LOOK_TYPE(false)
    , CAN_TX_DSP_TIMESTAMP(0)
    , CAN_TX_YAW_RATE_CALC(0.0)
    , CAN_TX_VEHICLE_SPEED_CALC(0.0)
    , CAN_TX_SCAN_INDEX(0)
    , CAN_TX_CURVATURE(0.0)  {
    }
  SrrStatus1_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , CAN_TX_LOOK_TYPE(false)
    , CAN_TX_DSP_TIMESTAMP(0)
    , CAN_TX_YAW_RATE_CALC(0.0)
    , CAN_TX_VEHICLE_SPEED_CALC(0.0)
    , CAN_TX_SCAN_INDEX(0)
    , CAN_TX_CURVATURE(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _CAN_TX_LOOK_TYPE_type;
  _CAN_TX_LOOK_TYPE_type CAN_TX_LOOK_TYPE;

   typedef uint32_t _CAN_TX_DSP_TIMESTAMP_type;
  _CAN_TX_DSP_TIMESTAMP_type CAN_TX_DSP_TIMESTAMP;

   typedef float _CAN_TX_YAW_RATE_CALC_type;
  _CAN_TX_YAW_RATE_CALC_type CAN_TX_YAW_RATE_CALC;

   typedef float _CAN_TX_VEHICLE_SPEED_CALC_type;
  _CAN_TX_VEHICLE_SPEED_CALC_type CAN_TX_VEHICLE_SPEED_CALC;

   typedef uint16_t _CAN_TX_SCAN_INDEX_type;
  _CAN_TX_SCAN_INDEX_type CAN_TX_SCAN_INDEX;

   typedef float _CAN_TX_CURVATURE_type;
  _CAN_TX_CURVATURE_type CAN_TX_CURVATURE;




  static const uint8_t CAN_TX_LOOK_TYPE_Medium_Look;
  static const uint8_t CAN_TX_LOOK_TYPE_Long_Look;

  typedef boost::shared_ptr< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> const> ConstPtr;

}; // struct SrrStatus1_

typedef ::delphi_srr_msgs::SrrStatus1_<std::allocator<void> > SrrStatus1;

typedef boost::shared_ptr< ::delphi_srr_msgs::SrrStatus1 > SrrStatus1Ptr;
typedef boost::shared_ptr< ::delphi_srr_msgs::SrrStatus1 const> SrrStatus1ConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const uint8_t
      SrrStatus1_<ContainerAllocator>::CAN_TX_LOOK_TYPE_Medium_Look =
        
           0
        
        ;
   

   
   template<typename ContainerAllocator> const uint8_t
      SrrStatus1_<ContainerAllocator>::CAN_TX_LOOK_TYPE_Long_Look =
        
           1
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_srr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_srr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_srr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7218c3cadae8e234a3242d37de450233";
  }

  static const char* value(const ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7218c3cadae8e234ULL;
  static const uint64_t static_value2 = 0xa3242d37de450233ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_srr_msgs/SrrStatus1";
  }

  static const char* value(const ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message file for srr_status1\n\
\n\
Header header\n\
\n\
bool      CAN_TX_LOOK_TYPE                        \n\
bool          CAN_TX_LOOK_TYPE_Medium_Look=0\n\
bool          CAN_TX_LOOK_TYPE_Long_Look=1\n\
\n\
uint32    CAN_TX_DSP_TIMESTAMP                     # ms\n\
\n\
float32   CAN_TX_YAW_RATE_CALC                     # deg/s\n\
\n\
float32   CAN_TX_VEHICLE_SPEED_CALC                # m/s\n\
\n\
uint16    CAN_TX_SCAN_INDEX                       \n\
\n\
float32   CAN_TX_CURVATURE                         # 1/m\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.CAN_TX_LOOK_TYPE);
      stream.next(m.CAN_TX_DSP_TIMESTAMP);
      stream.next(m.CAN_TX_YAW_RATE_CALC);
      stream.next(m.CAN_TX_VEHICLE_SPEED_CALC);
      stream.next(m.CAN_TX_SCAN_INDEX);
      stream.next(m.CAN_TX_CURVATURE);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SrrStatus1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_srr_msgs::SrrStatus1_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "CAN_TX_LOOK_TYPE: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CAN_TX_LOOK_TYPE);
    s << indent << "CAN_TX_DSP_TIMESTAMP: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.CAN_TX_DSP_TIMESTAMP);
    s << indent << "CAN_TX_YAW_RATE_CALC: ";
    Printer<float>::stream(s, indent + "  ", v.CAN_TX_YAW_RATE_CALC);
    s << indent << "CAN_TX_VEHICLE_SPEED_CALC: ";
    Printer<float>::stream(s, indent + "  ", v.CAN_TX_VEHICLE_SPEED_CALC);
    s << indent << "CAN_TX_SCAN_INDEX: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.CAN_TX_SCAN_INDEX);
    s << indent << "CAN_TX_CURVATURE: ";
    Printer<float>::stream(s, indent + "  ", v.CAN_TX_CURVATURE);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_SRR_MSGS_MESSAGE_SRRSTATUS1_H
