# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ibeo_msgs/Object2280.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ibeo_msgs.msg
import genpy

class Object2280(genpy.Message):
  _md5sum = "e8af58f0c0f3f183aa9baedd59c78e59"
  _type = "ibeo_msgs/Object2280"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 id
uint8 tracking_model
bool mobility_of_dyn_object_detected
bool motion_model_validated
uint32 object_age
time timestamp
uint16 object_prediction_age
uint8 classification
uint8 classification_certainty
uint32 classification_age
Point2Df object_box_center
Point2Df object_box_center_sigma
Point2Df object_box_size
float32 object_box_orientation_angle
float32 object_box_orientation_angle_sigma
Point2Df relative_velocity
Point2Df relative_velocity_sigma
Point2Df absolute_velocity
Point2Df absolute_velocity_sigma
uint8 number_of_contour_points
uint8 closest_point_index
uint16 reference_point_location
Point2Df reference_point_coordinate
Point2Df reference_point_coordinate_sigma
float32 reference_point_position_correction_coefficient
uint16 object_priority
float32 object_existence_measurement
Point2Df[] contour_point_list

# tracking_model values
uint8 DYNAMIC_MODEL=0
uint8 STATIC_MODEL=1

# classification values
uint8 UNCLASSIFIED=0
uint8 UNKNOWN_SMALL=1
uint8 UNKNOWN_BIG=2
uint8 PEDESTRIAN=3
uint8 BIKE=4
uint8 CAR=5
uint8 TRUCK=6
uint8 UNDER_DRIVABLE=12
uint8 OVER_DRIVABLE=13

# reference_point_location values
uint16 CENTER_OF_GRAVITY=0
uint16 FRONT_LEFT=1
uint16 FRONT_RIGHT=2
uint16 REAR_RIGHT=3
uint16 REAR_LEFT=4
uint16 FRONT_CENTER=5
uint16 RIGHT_CENTER=6
uint16 REAR_CENTER=7
uint16 LEFT_CENTER=8
uint16 OBJECT_CENTER=9
uint16 UNKNOWN=255


================================================================================
MSG: ibeo_msgs/Point2Df
float32 x
float32 y
"""
  # Pseudo-constants
  DYNAMIC_MODEL = 0
  STATIC_MODEL = 1
  UNCLASSIFIED = 0
  UNKNOWN_SMALL = 1
  UNKNOWN_BIG = 2
  PEDESTRIAN = 3
  BIKE = 4
  CAR = 5
  TRUCK = 6
  UNDER_DRIVABLE = 12
  OVER_DRIVABLE = 13
  CENTER_OF_GRAVITY = 0
  FRONT_LEFT = 1
  FRONT_RIGHT = 2
  REAR_RIGHT = 3
  REAR_LEFT = 4
  FRONT_CENTER = 5
  RIGHT_CENTER = 6
  REAR_CENTER = 7
  LEFT_CENTER = 8
  OBJECT_CENTER = 9
  UNKNOWN = 255

  __slots__ = ['id','tracking_model','mobility_of_dyn_object_detected','motion_model_validated','object_age','timestamp','object_prediction_age','classification','classification_certainty','classification_age','object_box_center','object_box_center_sigma','object_box_size','object_box_orientation_angle','object_box_orientation_angle_sigma','relative_velocity','relative_velocity_sigma','absolute_velocity','absolute_velocity_sigma','number_of_contour_points','closest_point_index','reference_point_location','reference_point_coordinate','reference_point_coordinate_sigma','reference_point_position_correction_coefficient','object_priority','object_existence_measurement','contour_point_list']
  _slot_types = ['uint16','uint8','bool','bool','uint32','time','uint16','uint8','uint8','uint32','ibeo_msgs/Point2Df','ibeo_msgs/Point2Df','ibeo_msgs/Point2Df','float32','float32','ibeo_msgs/Point2Df','ibeo_msgs/Point2Df','ibeo_msgs/Point2Df','ibeo_msgs/Point2Df','uint8','uint8','uint16','ibeo_msgs/Point2Df','ibeo_msgs/Point2Df','float32','uint16','float32','ibeo_msgs/Point2Df[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,tracking_model,mobility_of_dyn_object_detected,motion_model_validated,object_age,timestamp,object_prediction_age,classification,classification_certainty,classification_age,object_box_center,object_box_center_sigma,object_box_size,object_box_orientation_angle,object_box_orientation_angle_sigma,relative_velocity,relative_velocity_sigma,absolute_velocity,absolute_velocity_sigma,number_of_contour_points,closest_point_index,reference_point_location,reference_point_coordinate,reference_point_coordinate_sigma,reference_point_position_correction_coefficient,object_priority,object_existence_measurement,contour_point_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Object2280, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.tracking_model is None:
        self.tracking_model = 0
      if self.mobility_of_dyn_object_detected is None:
        self.mobility_of_dyn_object_detected = False
      if self.motion_model_validated is None:
        self.motion_model_validated = False
      if self.object_age is None:
        self.object_age = 0
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.object_prediction_age is None:
        self.object_prediction_age = 0
      if self.classification is None:
        self.classification = 0
      if self.classification_certainty is None:
        self.classification_certainty = 0
      if self.classification_age is None:
        self.classification_age = 0
      if self.object_box_center is None:
        self.object_box_center = ibeo_msgs.msg.Point2Df()
      if self.object_box_center_sigma is None:
        self.object_box_center_sigma = ibeo_msgs.msg.Point2Df()
      if self.object_box_size is None:
        self.object_box_size = ibeo_msgs.msg.Point2Df()
      if self.object_box_orientation_angle is None:
        self.object_box_orientation_angle = 0.
      if self.object_box_orientation_angle_sigma is None:
        self.object_box_orientation_angle_sigma = 0.
      if self.relative_velocity is None:
        self.relative_velocity = ibeo_msgs.msg.Point2Df()
      if self.relative_velocity_sigma is None:
        self.relative_velocity_sigma = ibeo_msgs.msg.Point2Df()
      if self.absolute_velocity is None:
        self.absolute_velocity = ibeo_msgs.msg.Point2Df()
      if self.absolute_velocity_sigma is None:
        self.absolute_velocity_sigma = ibeo_msgs.msg.Point2Df()
      if self.number_of_contour_points is None:
        self.number_of_contour_points = 0
      if self.closest_point_index is None:
        self.closest_point_index = 0
      if self.reference_point_location is None:
        self.reference_point_location = 0
      if self.reference_point_coordinate is None:
        self.reference_point_coordinate = ibeo_msgs.msg.Point2Df()
      if self.reference_point_coordinate_sigma is None:
        self.reference_point_coordinate_sigma = ibeo_msgs.msg.Point2Df()
      if self.reference_point_position_correction_coefficient is None:
        self.reference_point_position_correction_coefficient = 0.
      if self.object_priority is None:
        self.object_priority = 0
      if self.object_existence_measurement is None:
        self.object_existence_measurement = 0.
      if self.contour_point_list is None:
        self.contour_point_list = []
    else:
      self.id = 0
      self.tracking_model = 0
      self.mobility_of_dyn_object_detected = False
      self.motion_model_validated = False
      self.object_age = 0
      self.timestamp = genpy.Time()
      self.object_prediction_age = 0
      self.classification = 0
      self.classification_certainty = 0
      self.classification_age = 0
      self.object_box_center = ibeo_msgs.msg.Point2Df()
      self.object_box_center_sigma = ibeo_msgs.msg.Point2Df()
      self.object_box_size = ibeo_msgs.msg.Point2Df()
      self.object_box_orientation_angle = 0.
      self.object_box_orientation_angle_sigma = 0.
      self.relative_velocity = ibeo_msgs.msg.Point2Df()
      self.relative_velocity_sigma = ibeo_msgs.msg.Point2Df()
      self.absolute_velocity = ibeo_msgs.msg.Point2Df()
      self.absolute_velocity_sigma = ibeo_msgs.msg.Point2Df()
      self.number_of_contour_points = 0
      self.closest_point_index = 0
      self.reference_point_location = 0
      self.reference_point_coordinate = ibeo_msgs.msg.Point2Df()
      self.reference_point_coordinate_sigma = ibeo_msgs.msg.Point2Df()
      self.reference_point_position_correction_coefficient = 0.
      self.object_priority = 0
      self.object_existence_measurement = 0.
      self.contour_point_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_H3B3IH2BI16f2BH5fHf().pack(_x.id, _x.tracking_model, _x.mobility_of_dyn_object_detected, _x.motion_model_validated, _x.object_age, _x.timestamp.secs, _x.timestamp.nsecs, _x.object_prediction_age, _x.classification, _x.classification_certainty, _x.classification_age, _x.object_box_center.x, _x.object_box_center.y, _x.object_box_center_sigma.x, _x.object_box_center_sigma.y, _x.object_box_size.x, _x.object_box_size.y, _x.object_box_orientation_angle, _x.object_box_orientation_angle_sigma, _x.relative_velocity.x, _x.relative_velocity.y, _x.relative_velocity_sigma.x, _x.relative_velocity_sigma.y, _x.absolute_velocity.x, _x.absolute_velocity.y, _x.absolute_velocity_sigma.x, _x.absolute_velocity_sigma.y, _x.number_of_contour_points, _x.closest_point_index, _x.reference_point_location, _x.reference_point_coordinate.x, _x.reference_point_coordinate.y, _x.reference_point_coordinate_sigma.x, _x.reference_point_coordinate_sigma.y, _x.reference_point_position_correction_coefficient, _x.object_priority, _x.object_existence_measurement))
      length = len(self.contour_point_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.contour_point_list:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.object_box_center is None:
        self.object_box_center = ibeo_msgs.msg.Point2Df()
      if self.object_box_center_sigma is None:
        self.object_box_center_sigma = ibeo_msgs.msg.Point2Df()
      if self.object_box_size is None:
        self.object_box_size = ibeo_msgs.msg.Point2Df()
      if self.relative_velocity is None:
        self.relative_velocity = ibeo_msgs.msg.Point2Df()
      if self.relative_velocity_sigma is None:
        self.relative_velocity_sigma = ibeo_msgs.msg.Point2Df()
      if self.absolute_velocity is None:
        self.absolute_velocity = ibeo_msgs.msg.Point2Df()
      if self.absolute_velocity_sigma is None:
        self.absolute_velocity_sigma = ibeo_msgs.msg.Point2Df()
      if self.reference_point_coordinate is None:
        self.reference_point_coordinate = ibeo_msgs.msg.Point2Df()
      if self.reference_point_coordinate_sigma is None:
        self.reference_point_coordinate_sigma = ibeo_msgs.msg.Point2Df()
      if self.contour_point_list is None:
        self.contour_point_list = None
      end = 0
      _x = self
      start = end
      end += 119
      (_x.id, _x.tracking_model, _x.mobility_of_dyn_object_detected, _x.motion_model_validated, _x.object_age, _x.timestamp.secs, _x.timestamp.nsecs, _x.object_prediction_age, _x.classification, _x.classification_certainty, _x.classification_age, _x.object_box_center.x, _x.object_box_center.y, _x.object_box_center_sigma.x, _x.object_box_center_sigma.y, _x.object_box_size.x, _x.object_box_size.y, _x.object_box_orientation_angle, _x.object_box_orientation_angle_sigma, _x.relative_velocity.x, _x.relative_velocity.y, _x.relative_velocity_sigma.x, _x.relative_velocity_sigma.y, _x.absolute_velocity.x, _x.absolute_velocity.y, _x.absolute_velocity_sigma.x, _x.absolute_velocity_sigma.y, _x.number_of_contour_points, _x.closest_point_index, _x.reference_point_location, _x.reference_point_coordinate.x, _x.reference_point_coordinate.y, _x.reference_point_coordinate_sigma.x, _x.reference_point_coordinate_sigma.y, _x.reference_point_position_correction_coefficient, _x.object_priority, _x.object_existence_measurement,) = _get_struct_H3B3IH2BI16f2BH5fHf().unpack(str[start:end])
      self.mobility_of_dyn_object_detected = bool(self.mobility_of_dyn_object_detected)
      self.motion_model_validated = bool(self.motion_model_validated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.contour_point_list = []
      for i in range(0, length):
        val1 = ibeo_msgs.msg.Point2Df()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.contour_point_list.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_H3B3IH2BI16f2BH5fHf().pack(_x.id, _x.tracking_model, _x.mobility_of_dyn_object_detected, _x.motion_model_validated, _x.object_age, _x.timestamp.secs, _x.timestamp.nsecs, _x.object_prediction_age, _x.classification, _x.classification_certainty, _x.classification_age, _x.object_box_center.x, _x.object_box_center.y, _x.object_box_center_sigma.x, _x.object_box_center_sigma.y, _x.object_box_size.x, _x.object_box_size.y, _x.object_box_orientation_angle, _x.object_box_orientation_angle_sigma, _x.relative_velocity.x, _x.relative_velocity.y, _x.relative_velocity_sigma.x, _x.relative_velocity_sigma.y, _x.absolute_velocity.x, _x.absolute_velocity.y, _x.absolute_velocity_sigma.x, _x.absolute_velocity_sigma.y, _x.number_of_contour_points, _x.closest_point_index, _x.reference_point_location, _x.reference_point_coordinate.x, _x.reference_point_coordinate.y, _x.reference_point_coordinate_sigma.x, _x.reference_point_coordinate_sigma.y, _x.reference_point_position_correction_coefficient, _x.object_priority, _x.object_existence_measurement))
      length = len(self.contour_point_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.contour_point_list:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.object_box_center is None:
        self.object_box_center = ibeo_msgs.msg.Point2Df()
      if self.object_box_center_sigma is None:
        self.object_box_center_sigma = ibeo_msgs.msg.Point2Df()
      if self.object_box_size is None:
        self.object_box_size = ibeo_msgs.msg.Point2Df()
      if self.relative_velocity is None:
        self.relative_velocity = ibeo_msgs.msg.Point2Df()
      if self.relative_velocity_sigma is None:
        self.relative_velocity_sigma = ibeo_msgs.msg.Point2Df()
      if self.absolute_velocity is None:
        self.absolute_velocity = ibeo_msgs.msg.Point2Df()
      if self.absolute_velocity_sigma is None:
        self.absolute_velocity_sigma = ibeo_msgs.msg.Point2Df()
      if self.reference_point_coordinate is None:
        self.reference_point_coordinate = ibeo_msgs.msg.Point2Df()
      if self.reference_point_coordinate_sigma is None:
        self.reference_point_coordinate_sigma = ibeo_msgs.msg.Point2Df()
      if self.contour_point_list is None:
        self.contour_point_list = None
      end = 0
      _x = self
      start = end
      end += 119
      (_x.id, _x.tracking_model, _x.mobility_of_dyn_object_detected, _x.motion_model_validated, _x.object_age, _x.timestamp.secs, _x.timestamp.nsecs, _x.object_prediction_age, _x.classification, _x.classification_certainty, _x.classification_age, _x.object_box_center.x, _x.object_box_center.y, _x.object_box_center_sigma.x, _x.object_box_center_sigma.y, _x.object_box_size.x, _x.object_box_size.y, _x.object_box_orientation_angle, _x.object_box_orientation_angle_sigma, _x.relative_velocity.x, _x.relative_velocity.y, _x.relative_velocity_sigma.x, _x.relative_velocity_sigma.y, _x.absolute_velocity.x, _x.absolute_velocity.y, _x.absolute_velocity_sigma.x, _x.absolute_velocity_sigma.y, _x.number_of_contour_points, _x.closest_point_index, _x.reference_point_location, _x.reference_point_coordinate.x, _x.reference_point_coordinate.y, _x.reference_point_coordinate_sigma.x, _x.reference_point_coordinate_sigma.y, _x.reference_point_position_correction_coefficient, _x.object_priority, _x.object_existence_measurement,) = _get_struct_H3B3IH2BI16f2BH5fHf().unpack(str[start:end])
      self.mobility_of_dyn_object_detected = bool(self.mobility_of_dyn_object_detected)
      self.motion_model_validated = bool(self.motion_model_validated)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.contour_point_list = []
      for i in range(0, length):
        val1 = ibeo_msgs.msg.Point2Df()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.contour_point_list.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H3B3IH2BI16f2BH5fHf = None
def _get_struct_H3B3IH2BI16f2BH5fHf():
    global _struct_H3B3IH2BI16f2BH5fHf
    if _struct_H3B3IH2BI16f2BH5fHf is None:
        _struct_H3B3IH2BI16f2BH5fHf = struct.Struct("<H3B3IH2BI16f2BH5fHf")
    return _struct_H3B3IH2BI16f2BH5fHf
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
