# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ibeo_msgs/ScanData2204.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import ibeo_msgs.msg
import std_msgs.msg

class ScanData2204(genpy.Message):
  _md5sum = "373528bb1a7104132613bbfa12f008fd"
  _type = "ibeo_msgs/ScanData2204"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

IbeoDataHeader ibeo_header
uint64 scan_start_time
uint32 scan_end_time_offset
bool ground_labeled
bool dirt_labeled
bool rain_labeled
bool fused_scan
uint8 mirror_side
uint8 coordinate_system
uint16 scan_number
uint16 scan_points
uint16 number_of_scanner_infos
ScannerInfo2204[] scanner_info_list
ScanPoint2204[] scan_point_list

# mirror_side values
uint8 FRONT=0
uint8 REAR=1

# coordinate_system values
uint8 SCANNER=0
uint8 VEHICLE=1

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: ibeo_msgs/IbeoDataHeader
uint32 previous_message_size
uint32 message_size
uint8 device_id
uint16 data_type_id
time stamp

================================================================================
MSG: ibeo_msgs/ScannerInfo2204
uint8 device_id
uint8 scanner_type
uint16 scan_number
float32 start_angle
float32 end_angle
float32 yaw_angle
float32 pitch_angle
float32 roll_angle
float32 offset_x
float32 offset_y
float32 offset_z

# scanner_type values
uint8 ALASCA_XT=3
uint8 LUX_ECU=4
uint8 LUX_PROTOTYPE=5
uint8 LUX=6
uint8 SCALA_B1=96

================================================================================
MSG: ibeo_msgs/ScanPoint2204
float32 x_position
float32 y_position
float32 z_position
float32 echo_width
uint8 device_id
uint8 layer
uint8 echo
uint32 time_offset
bool ground
bool dirt
bool precipitation
"""
  # Pseudo-constants
  FRONT = 0
  REAR = 1
  SCANNER = 0
  VEHICLE = 1

  __slots__ = ['header','ibeo_header','scan_start_time','scan_end_time_offset','ground_labeled','dirt_labeled','rain_labeled','fused_scan','mirror_side','coordinate_system','scan_number','scan_points','number_of_scanner_infos','scanner_info_list','scan_point_list']
  _slot_types = ['std_msgs/Header','ibeo_msgs/IbeoDataHeader','uint64','uint32','bool','bool','bool','bool','uint8','uint8','uint16','uint16','uint16','ibeo_msgs/ScannerInfo2204[]','ibeo_msgs/ScanPoint2204[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ibeo_header,scan_start_time,scan_end_time_offset,ground_labeled,dirt_labeled,rain_labeled,fused_scan,mirror_side,coordinate_system,scan_number,scan_points,number_of_scanner_infos,scanner_info_list,scan_point_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ScanData2204, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ibeo_header is None:
        self.ibeo_header = ibeo_msgs.msg.IbeoDataHeader()
      if self.scan_start_time is None:
        self.scan_start_time = 0
      if self.scan_end_time_offset is None:
        self.scan_end_time_offset = 0
      if self.ground_labeled is None:
        self.ground_labeled = False
      if self.dirt_labeled is None:
        self.dirt_labeled = False
      if self.rain_labeled is None:
        self.rain_labeled = False
      if self.fused_scan is None:
        self.fused_scan = False
      if self.mirror_side is None:
        self.mirror_side = 0
      if self.coordinate_system is None:
        self.coordinate_system = 0
      if self.scan_number is None:
        self.scan_number = 0
      if self.scan_points is None:
        self.scan_points = 0
      if self.number_of_scanner_infos is None:
        self.number_of_scanner_infos = 0
      if self.scanner_info_list is None:
        self.scanner_info_list = []
      if self.scan_point_list is None:
        self.scan_point_list = []
    else:
      self.header = std_msgs.msg.Header()
      self.ibeo_header = ibeo_msgs.msg.IbeoDataHeader()
      self.scan_start_time = 0
      self.scan_end_time_offset = 0
      self.ground_labeled = False
      self.dirt_labeled = False
      self.rain_labeled = False
      self.fused_scan = False
      self.mirror_side = 0
      self.coordinate_system = 0
      self.scan_number = 0
      self.scan_points = 0
      self.number_of_scanner_infos = 0
      self.scanner_info_list = []
      self.scan_point_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2IBH2IQI6B3H().pack(_x.ibeo_header.previous_message_size, _x.ibeo_header.message_size, _x.ibeo_header.device_id, _x.ibeo_header.data_type_id, _x.ibeo_header.stamp.secs, _x.ibeo_header.stamp.nsecs, _x.scan_start_time, _x.scan_end_time_offset, _x.ground_labeled, _x.dirt_labeled, _x.rain_labeled, _x.fused_scan, _x.mirror_side, _x.coordinate_system, _x.scan_number, _x.scan_points, _x.number_of_scanner_infos))
      length = len(self.scanner_info_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.scanner_info_list:
        _x = val1
        buff.write(_get_struct_2BH8f().pack(_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.yaw_angle, _x.pitch_angle, _x.roll_angle, _x.offset_x, _x.offset_y, _x.offset_z))
      length = len(self.scan_point_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.scan_point_list:
        _x = val1
        buff.write(_get_struct_4f3BI3B().pack(_x.x_position, _x.y_position, _x.z_position, _x.echo_width, _x.device_id, _x.layer, _x.echo, _x.time_offset, _x.ground, _x.dirt, _x.precipitation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ibeo_header is None:
        self.ibeo_header = ibeo_msgs.msg.IbeoDataHeader()
      if self.scanner_info_list is None:
        self.scanner_info_list = None
      if self.scan_point_list is None:
        self.scan_point_list = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 43
      (_x.ibeo_header.previous_message_size, _x.ibeo_header.message_size, _x.ibeo_header.device_id, _x.ibeo_header.data_type_id, _x.ibeo_header.stamp.secs, _x.ibeo_header.stamp.nsecs, _x.scan_start_time, _x.scan_end_time_offset, _x.ground_labeled, _x.dirt_labeled, _x.rain_labeled, _x.fused_scan, _x.mirror_side, _x.coordinate_system, _x.scan_number, _x.scan_points, _x.number_of_scanner_infos,) = _get_struct_2IBH2IQI6B3H().unpack(str[start:end])
      self.ground_labeled = bool(self.ground_labeled)
      self.dirt_labeled = bool(self.dirt_labeled)
      self.rain_labeled = bool(self.rain_labeled)
      self.fused_scan = bool(self.fused_scan)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.scanner_info_list = []
      for i in range(0, length):
        val1 = ibeo_msgs.msg.ScannerInfo2204()
        _x = val1
        start = end
        end += 36
        (_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.yaw_angle, _x.pitch_angle, _x.roll_angle, _x.offset_x, _x.offset_y, _x.offset_z,) = _get_struct_2BH8f().unpack(str[start:end])
        self.scanner_info_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.scan_point_list = []
      for i in range(0, length):
        val1 = ibeo_msgs.msg.ScanPoint2204()
        _x = val1
        start = end
        end += 26
        (_x.x_position, _x.y_position, _x.z_position, _x.echo_width, _x.device_id, _x.layer, _x.echo, _x.time_offset, _x.ground, _x.dirt, _x.precipitation,) = _get_struct_4f3BI3B().unpack(str[start:end])
        val1.ground = bool(val1.ground)
        val1.dirt = bool(val1.dirt)
        val1.precipitation = bool(val1.precipitation)
        self.scan_point_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2IBH2IQI6B3H().pack(_x.ibeo_header.previous_message_size, _x.ibeo_header.message_size, _x.ibeo_header.device_id, _x.ibeo_header.data_type_id, _x.ibeo_header.stamp.secs, _x.ibeo_header.stamp.nsecs, _x.scan_start_time, _x.scan_end_time_offset, _x.ground_labeled, _x.dirt_labeled, _x.rain_labeled, _x.fused_scan, _x.mirror_side, _x.coordinate_system, _x.scan_number, _x.scan_points, _x.number_of_scanner_infos))
      length = len(self.scanner_info_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.scanner_info_list:
        _x = val1
        buff.write(_get_struct_2BH8f().pack(_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.yaw_angle, _x.pitch_angle, _x.roll_angle, _x.offset_x, _x.offset_y, _x.offset_z))
      length = len(self.scan_point_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.scan_point_list:
        _x = val1
        buff.write(_get_struct_4f3BI3B().pack(_x.x_position, _x.y_position, _x.z_position, _x.echo_width, _x.device_id, _x.layer, _x.echo, _x.time_offset, _x.ground, _x.dirt, _x.precipitation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ibeo_header is None:
        self.ibeo_header = ibeo_msgs.msg.IbeoDataHeader()
      if self.scanner_info_list is None:
        self.scanner_info_list = None
      if self.scan_point_list is None:
        self.scan_point_list = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 43
      (_x.ibeo_header.previous_message_size, _x.ibeo_header.message_size, _x.ibeo_header.device_id, _x.ibeo_header.data_type_id, _x.ibeo_header.stamp.secs, _x.ibeo_header.stamp.nsecs, _x.scan_start_time, _x.scan_end_time_offset, _x.ground_labeled, _x.dirt_labeled, _x.rain_labeled, _x.fused_scan, _x.mirror_side, _x.coordinate_system, _x.scan_number, _x.scan_points, _x.number_of_scanner_infos,) = _get_struct_2IBH2IQI6B3H().unpack(str[start:end])
      self.ground_labeled = bool(self.ground_labeled)
      self.dirt_labeled = bool(self.dirt_labeled)
      self.rain_labeled = bool(self.rain_labeled)
      self.fused_scan = bool(self.fused_scan)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.scanner_info_list = []
      for i in range(0, length):
        val1 = ibeo_msgs.msg.ScannerInfo2204()
        _x = val1
        start = end
        end += 36
        (_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.yaw_angle, _x.pitch_angle, _x.roll_angle, _x.offset_x, _x.offset_y, _x.offset_z,) = _get_struct_2BH8f().unpack(str[start:end])
        self.scanner_info_list.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.scan_point_list = []
      for i in range(0, length):
        val1 = ibeo_msgs.msg.ScanPoint2204()
        _x = val1
        start = end
        end += 26
        (_x.x_position, _x.y_position, _x.z_position, _x.echo_width, _x.device_id, _x.layer, _x.echo, _x.time_offset, _x.ground, _x.dirt, _x.precipitation,) = _get_struct_4f3BI3B().unpack(str[start:end])
        val1.ground = bool(val1.ground)
        val1.dirt = bool(val1.dirt)
        val1.precipitation = bool(val1.precipitation)
        self.scan_point_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2IBH2IQI6B3H = None
def _get_struct_2IBH2IQI6B3H():
    global _struct_2IBH2IQI6B3H
    if _struct_2IBH2IQI6B3H is None:
        _struct_2IBH2IQI6B3H = struct.Struct("<2IBH2IQI6B3H")
    return _struct_2IBH2IQI6B3H
_struct_4f3BI3B = None
def _get_struct_4f3BI3B():
    global _struct_4f3BI3B
    if _struct_4f3BI3B is None:
        _struct_4f3BI3B = struct.Struct("<4f3BI3B")
    return _struct_4f3BI3B
_struct_2BH8f = None
def _get_struct_2BH8f():
    global _struct_2BH8f
    if _struct_2BH8f is None:
        _struct_2BH8f = struct.Struct("<2BH8f")
    return _struct_2BH8f
