# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ibeo_msgs/ScannerInfo2205.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ibeo_msgs.msg
import genpy

class ScannerInfo2205(genpy.Message):
  _md5sum = "79f253f5127e7e8a6ca7b4129fa5c4b1"
  _type = "ibeo_msgs/ScannerInfo2205"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 device_id
uint8 scanner_type
uint16 scan_number
float32 start_angle
float32 end_angle
time scan_start_time
time scan_end_time
time scan_start_time_from_device
time scan_end_time_from_device
float32 scan_frequency
float32 beam_tilt
uint32 scan_flags
MountingPositionF mounting_position
ResolutionInfo[8] resolutions

# scanner_type values
uint8 ALASCA_XT=3
uint8 LUX_ECU=4
uint8 LUX_PROTOTYPE=5
uint8 LUX=6
uint8 SCALA_B1=96

================================================================================
MSG: ibeo_msgs/MountingPositionF
float32 yaw_angle
float32 pitch_angle
float32 roll_angle
float32 x_position
float32 y_position
float32 z_position

================================================================================
MSG: ibeo_msgs/ResolutionInfo
float32 resolution_start_angle
float32 resolution
"""
  # Pseudo-constants
  ALASCA_XT = 3
  LUX_ECU = 4
  LUX_PROTOTYPE = 5
  LUX = 6
  SCALA_B1 = 96

  __slots__ = ['device_id','scanner_type','scan_number','start_angle','end_angle','scan_start_time','scan_end_time','scan_start_time_from_device','scan_end_time_from_device','scan_frequency','beam_tilt','scan_flags','mounting_position','resolutions']
  _slot_types = ['uint8','uint8','uint16','float32','float32','time','time','time','time','float32','float32','uint32','ibeo_msgs/MountingPositionF','ibeo_msgs/ResolutionInfo[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       device_id,scanner_type,scan_number,start_angle,end_angle,scan_start_time,scan_end_time,scan_start_time_from_device,scan_end_time_from_device,scan_frequency,beam_tilt,scan_flags,mounting_position,resolutions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ScannerInfo2205, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.device_id is None:
        self.device_id = 0
      if self.scanner_type is None:
        self.scanner_type = 0
      if self.scan_number is None:
        self.scan_number = 0
      if self.start_angle is None:
        self.start_angle = 0.
      if self.end_angle is None:
        self.end_angle = 0.
      if self.scan_start_time is None:
        self.scan_start_time = genpy.Time()
      if self.scan_end_time is None:
        self.scan_end_time = genpy.Time()
      if self.scan_start_time_from_device is None:
        self.scan_start_time_from_device = genpy.Time()
      if self.scan_end_time_from_device is None:
        self.scan_end_time_from_device = genpy.Time()
      if self.scan_frequency is None:
        self.scan_frequency = 0.
      if self.beam_tilt is None:
        self.beam_tilt = 0.
      if self.scan_flags is None:
        self.scan_flags = 0
      if self.mounting_position is None:
        self.mounting_position = ibeo_msgs.msg.MountingPositionF()
      if self.resolutions is None:
        self.resolutions = [ibeo_msgs.msg.ResolutionInfo() for _ in range(8)]
    else:
      self.device_id = 0
      self.scanner_type = 0
      self.scan_number = 0
      self.start_angle = 0.
      self.end_angle = 0.
      self.scan_start_time = genpy.Time()
      self.scan_end_time = genpy.Time()
      self.scan_start_time_from_device = genpy.Time()
      self.scan_end_time_from_device = genpy.Time()
      self.scan_frequency = 0.
      self.beam_tilt = 0.
      self.scan_flags = 0
      self.mounting_position = ibeo_msgs.msg.MountingPositionF()
      self.resolutions = [ibeo_msgs.msg.ResolutionInfo() for _ in range(8)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2BH2f8I2fI6f().pack(_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.scan_start_time.secs, _x.scan_start_time.nsecs, _x.scan_end_time.secs, _x.scan_end_time.nsecs, _x.scan_start_time_from_device.secs, _x.scan_start_time_from_device.nsecs, _x.scan_end_time_from_device.secs, _x.scan_end_time_from_device.nsecs, _x.scan_frequency, _x.beam_tilt, _x.scan_flags, _x.mounting_position.yaw_angle, _x.mounting_position.pitch_angle, _x.mounting_position.roll_angle, _x.mounting_position.x_position, _x.mounting_position.y_position, _x.mounting_position.z_position))
      for val1 in self.resolutions:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.resolution_start_angle, _x.resolution))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.scan_start_time is None:
        self.scan_start_time = genpy.Time()
      if self.scan_end_time is None:
        self.scan_end_time = genpy.Time()
      if self.scan_start_time_from_device is None:
        self.scan_start_time_from_device = genpy.Time()
      if self.scan_end_time_from_device is None:
        self.scan_end_time_from_device = genpy.Time()
      if self.mounting_position is None:
        self.mounting_position = ibeo_msgs.msg.MountingPositionF()
      if self.resolutions is None:
        self.resolutions = None
      end = 0
      _x = self
      start = end
      end += 80
      (_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.scan_start_time.secs, _x.scan_start_time.nsecs, _x.scan_end_time.secs, _x.scan_end_time.nsecs, _x.scan_start_time_from_device.secs, _x.scan_start_time_from_device.nsecs, _x.scan_end_time_from_device.secs, _x.scan_end_time_from_device.nsecs, _x.scan_frequency, _x.beam_tilt, _x.scan_flags, _x.mounting_position.yaw_angle, _x.mounting_position.pitch_angle, _x.mounting_position.roll_angle, _x.mounting_position.x_position, _x.mounting_position.y_position, _x.mounting_position.z_position,) = _get_struct_2BH2f8I2fI6f().unpack(str[start:end])
      self.resolutions = []
      for i in range(0, 8):
        val1 = ibeo_msgs.msg.ResolutionInfo()
        _x = val1
        start = end
        end += 8
        (_x.resolution_start_angle, _x.resolution,) = _get_struct_2f().unpack(str[start:end])
        self.resolutions.append(val1)
      self.scan_start_time.canon()
      self.scan_end_time.canon()
      self.scan_start_time_from_device.canon()
      self.scan_end_time_from_device.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2BH2f8I2fI6f().pack(_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.scan_start_time.secs, _x.scan_start_time.nsecs, _x.scan_end_time.secs, _x.scan_end_time.nsecs, _x.scan_start_time_from_device.secs, _x.scan_start_time_from_device.nsecs, _x.scan_end_time_from_device.secs, _x.scan_end_time_from_device.nsecs, _x.scan_frequency, _x.beam_tilt, _x.scan_flags, _x.mounting_position.yaw_angle, _x.mounting_position.pitch_angle, _x.mounting_position.roll_angle, _x.mounting_position.x_position, _x.mounting_position.y_position, _x.mounting_position.z_position))
      for val1 in self.resolutions:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.resolution_start_angle, _x.resolution))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.scan_start_time is None:
        self.scan_start_time = genpy.Time()
      if self.scan_end_time is None:
        self.scan_end_time = genpy.Time()
      if self.scan_start_time_from_device is None:
        self.scan_start_time_from_device = genpy.Time()
      if self.scan_end_time_from_device is None:
        self.scan_end_time_from_device = genpy.Time()
      if self.mounting_position is None:
        self.mounting_position = ibeo_msgs.msg.MountingPositionF()
      if self.resolutions is None:
        self.resolutions = None
      end = 0
      _x = self
      start = end
      end += 80
      (_x.device_id, _x.scanner_type, _x.scan_number, _x.start_angle, _x.end_angle, _x.scan_start_time.secs, _x.scan_start_time.nsecs, _x.scan_end_time.secs, _x.scan_end_time.nsecs, _x.scan_start_time_from_device.secs, _x.scan_start_time_from_device.nsecs, _x.scan_end_time_from_device.secs, _x.scan_end_time_from_device.nsecs, _x.scan_frequency, _x.beam_tilt, _x.scan_flags, _x.mounting_position.yaw_angle, _x.mounting_position.pitch_angle, _x.mounting_position.roll_angle, _x.mounting_position.x_position, _x.mounting_position.y_position, _x.mounting_position.z_position,) = _get_struct_2BH2f8I2fI6f().unpack(str[start:end])
      self.resolutions = []
      for i in range(0, 8):
        val1 = ibeo_msgs.msg.ResolutionInfo()
        _x = val1
        start = end
        end += 8
        (_x.resolution_start_angle, _x.resolution,) = _get_struct_2f().unpack(str[start:end])
        self.resolutions.append(val1)
      self.scan_start_time.canon()
      self.scan_end_time.canon()
      self.scan_start_time_from_device.canon()
      self.scan_end_time_from_device.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BH2f8I2fI6f = None
def _get_struct_2BH2f8I2fI6f():
    global _struct_2BH2f8I2fI6f
    if _struct_2BH2f8I2fI6f is None:
        _struct_2BH2f8I2fI6f = struct.Struct("<2BH2f8I2fI6f")
    return _struct_2BH2f8I2fI6f
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
