(cl:defpackage radar_msgs-msg
  (:use )
  (:export
   "<RADARDETECTION>"
   "RADARDETECTION"
   "<RADARDETECTIONARRAY>"
   "RADARDETECTIONARRAY"
   "<RADARDETECTIONSTAMPED>"
   "RADARDETECTIONSTAMPED"
   "<RADARERRORSTATUS>"
   "RADARERRORSTATUS"
   "<RADARSTATUS>"
   "RADARSTATUS"
   "<RADARTRACK>"
   "RADARTRACK"
   "<RADARTRACKARRAY>"
   "RADARTRACKARRAY"
   "<RADARTRACKSTAMPED>"
   "RADARTRACKSTAMPED"
  ))

