(cl:in-package ibeo_msgs-msg)
(cl:export '(ID-VAL
          ID
          TRACKED_PROPERTIES_AVAILABLE-VAL
          TRACKED_PROPERTIES_AVAILABLE
          UNTRACKED_PROPERTIES_AVAILABLE-VAL
          UNTRACKED_PROPERTIES_AVAILABLE
          TRACKED_PROPERTIES-VAL
          TRACKED_PROPERTIES
          UNTRACKED_PROPERTIES-VAL
          UNTRACKED_PROPERTIES
))