(cl:in-package ibeo_msgs-msg)
(cl:export '(RELATIVE_TIME_OF_MEASUREMENT-VAL
          RELATIVE_TIME_OF_MEASUREMENT
          POSITION_CLOSEST_POINT-VAL
          POSITION_CLOSEST_POINT
          OBJECT_BOX_SIZE-VAL
          OBJECT_BOX_SIZE
          OBJECT_BOX_SIZE_SIGMA-VAL
          OBJECT_BOX_SIZE_SIGMA
          OBJECT_BOX_ORIENTATION-VAL
          OBJECT_BOX_ORIENTATION
          OBJECT_BOX_ORIENTATION_SIGMA-VAL
          OBJECT_BOX_ORIENTATION_SIGMA
          TRACKING_POINT_COORDINATE-VAL
          TRACKING_POINT_COORDINATE
          TRACKING_POINT_COORDINATE_SIGMA-VAL
          TRACKING_POINT_COORDINATE_SIGMA
          NUMBER_OF_CONTOUR_POINTS-VAL
          NUMBER_OF_CONTOUR_POINTS
          CONTOUR_POINT_LIST-VAL
          CONTOUR_POINT_LIST
))