(cl:in-package ibeo_msgs-msg)
(cl:export '(DEVICE_ID-VAL
          DEVICE_ID
          SCANNER_TYPE-VAL
          SCANNER_TYPE
          SCAN_NUMBER-VAL
          SCAN_NUMBER
          START_ANGLE-VAL
          START_ANGLE
          END_ANGLE-VAL
          END_ANGLE
          SCAN_START_TIME-VAL
          SCAN_START_TIME
          SCAN_END_TIME-VAL
          SCAN_END_TIME
          SCAN_START_TIME_FROM_DEVICE-VAL
          SCAN_START_TIME_FROM_DEVICE
          SCAN_END_TIME_FROM_DEVICE-VAL
          SCAN_END_TIME_FROM_DEVICE
          SCAN_FREQUENCY-VAL
          SCAN_FREQUENCY
          BEAM_TILT-VAL
          BEAM_TILT
          SCAN_FLAGS-VAL
          SCAN_FLAGS
          MOUNTING_POSITION-VAL
          MOUNTING_POSITION
          RESOLUTIONS-VAL
          RESOLUTIONS
))