(cl:in-package ibeo_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IBEO_HEADER-VAL
          IBEO_HEADER
          TIMESTAMP-VAL
          TIMESTAMP
          SCAN_NUMBER-VAL
          SCAN_NUMBER
          ERROR_FLAGS-VAL
          ERROR_FLAGS
          LONGITUDINAL_VELOCITY-VAL
          LONGITUDINAL_VELOCITY
          STEERING_WHEEL_ANGLE-VAL
          STEERING_WHEEL_ANGLE
          FRONT_WHEEL_ANGLE-VAL
          FRONT_WHEEL_ANGLE
          X_POSITION-VAL
          X_POSITION
          Y_POSITION-VAL
          Y_POSITION
          COURSE_ANGLE-VAL
          COURSE_ANGLE
          TIME_DIFFERENCE-VAL
          TIME_DIFFERENCE
          X_DIFFERENCE-VAL
          X_DIFFERENCE
          Y_DIFFERENCE-VAL
          Y_DIFFERENCE
          HEADING_DIFFERENCE-VAL
          HEADING_DIFFERENCE
          CURRENT_YAW_RATE-VAL
          CURRENT_YAW_RATE
))