# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kartech_linear_actuator_msgs/ScheduledReportRatesReq.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kartech_linear_actuator_msgs.msg
import std_msgs.msg

class ScheduledReportRatesReq(genpy.Message):
  _md5sum = "26225aeadc02f4f458a0546ea8c99d87"
  _type = "kartech_linear_actuator_msgs/ScheduledReportRatesReq"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
bool confirm
ReportIndex index_1
uint16 index_1_report_time    # How often to publish the requested report in ms.
ReportIndex index_2           # If this is set to REPORT_NONE_INDEX then only the first index will be reported.
uint16 index_2_report_time    # Ignored if index_2 is set to REPORT_NONE_INDEX.

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: kartech_linear_actuator_msgs/ReportIndex
uint8 POSITION_REPORT_INDEX = 128
uint8 MOTOR_CURRENT_REPORT_INDEX = 129
uint8 ENHANCED_POSITION_REPORT_INDEX = 152
uint8 UNIQUE_DEVICE_ID_REPORTS_INDEX = 167
uint8 SOFTWARE_REVISION_REPORT_INDEX = 229
uint8 ZEROING_MESSAGE_REPORT_INDEX = 238

uint8 report_index
"""
  __slots__ = ['header','confirm','index_1','index_1_report_time','index_2','index_2_report_time']
  _slot_types = ['std_msgs/Header','bool','kartech_linear_actuator_msgs/ReportIndex','uint16','kartech_linear_actuator_msgs/ReportIndex','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,confirm,index_1,index_1_report_time,index_2,index_2_report_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ScheduledReportRatesReq, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.confirm is None:
        self.confirm = False
      if self.index_1 is None:
        self.index_1 = kartech_linear_actuator_msgs.msg.ReportIndex()
      if self.index_1_report_time is None:
        self.index_1_report_time = 0
      if self.index_2 is None:
        self.index_2 = kartech_linear_actuator_msgs.msg.ReportIndex()
      if self.index_2_report_time is None:
        self.index_2_report_time = 0
    else:
      self.header = std_msgs.msg.Header()
      self.confirm = False
      self.index_1 = kartech_linear_actuator_msgs.msg.ReportIndex()
      self.index_1_report_time = 0
      self.index_2 = kartech_linear_actuator_msgs.msg.ReportIndex()
      self.index_2_report_time = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2BHBH().pack(_x.confirm, _x.index_1.report_index, _x.index_1_report_time, _x.index_2.report_index, _x.index_2_report_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.index_1 is None:
        self.index_1 = kartech_linear_actuator_msgs.msg.ReportIndex()
      if self.index_2 is None:
        self.index_2 = kartech_linear_actuator_msgs.msg.ReportIndex()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.confirm, _x.index_1.report_index, _x.index_1_report_time, _x.index_2.report_index, _x.index_2_report_time,) = _get_struct_2BHBH().unpack(str[start:end])
      self.confirm = bool(self.confirm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2BHBH().pack(_x.confirm, _x.index_1.report_index, _x.index_1_report_time, _x.index_2.report_index, _x.index_2_report_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.index_1 is None:
        self.index_1 = kartech_linear_actuator_msgs.msg.ReportIndex()
      if self.index_2 is None:
        self.index_2 = kartech_linear_actuator_msgs.msg.ReportIndex()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.confirm, _x.index_1.report_index, _x.index_1_report_time, _x.index_2.report_index, _x.index_2_report_time,) = _get_struct_2BHBH().unpack(str[start:end])
      self.confirm = bool(self.confirm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2BHBH = None
def _get_struct_2BHBH():
    global _struct_2BHBH
    if _struct_2BHBH is None:
        _struct_2BHBH = struct.Struct("<2BHBH")
    return _struct_2BHBH
