(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MRRXCPDAQRESPBYTE7-VAL
          MRRXCPDAQRESPBYTE7
          MRRXCPDAQRESPBYTE6-VAL
          MRRXCPDAQRESPBYTE6
          MRRXCPDAQRESPBYTE5-VAL
          MRRXCPDAQRESPBYTE5
          MRRXCPDAQRESPBYTE4-VAL
          MRRXCPDAQRESPBYTE4
          MRRXCPDAQRESPBYTE3-VAL
          MRRXCPDAQRESPBYTE3
          MRRXCPDAQRESPBYTE2-VAL
          MRRXCPDAQRESPBYTE2
          MRRXCPDAQRESPBYTE1-VAL
          MRRXCPDAQRESPBYTE1
          MRRXCPDAQRESPBYTE0-VAL
          MRRXCPDAQRESPBYTE0
))