(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MRRXCPDTORESPBYTE7-VAL
          MRRXCPDTORESPBYTE7
          MRRXCPDTORESPBYTE6-VAL
          MRRXCPDTORESPBYTE6
          MRRXCPDTORESPBYTE5-VAL
          MRRXCPDTORESPBYTE5
          MRRXCPDTORESPBYTE4-VAL
          MRRXCPDTORESPBYTE4
          MRRXCPDTORESPBYTE3-VAL
          MRRXCPDTORESPBYTE3
          MRRXCPDTORESPBYTE2-VAL
          MRRXCPDTORESPBYTE2
          MRRXCPDTORESPBYTE1-VAL
          MRRXCPDTORESPBYTE1
          MRRXCPDTORESPBYTE0-VAL
          MRRXCPDTORESPBYTE0
))