(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MRRXCPDTOCMDBYTE7-VAL
          MRRXCPDTOCMDBYTE7
          MRRXCPDTOCMDBYTE6-VAL
          MRRXCPDTOCMDBYTE6
          MRRXCPDTOCMDBYTE5-VAL
          MRRXCPDTOCMDBYTE5
          MRRXCPDTOCMDBYTE4-VAL
          MRRXCPDTOCMDBYTE4
          MRRXCPDTOCMDBYTE3-VAL
          MRRXCPDTOCMDBYTE3
          MRRXCPDTOCMDBYTE2-VAL
          MRRXCPDTOCMDBYTE2
          MRRXCPDTOCMDBYTE1-VAL
          MRRXCPDTOCMDBYTE1
          MRRXCPDTOCMDBYTE0-VAL
          MRRXCPDTOCMDBYTE0
))