(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IPMAPCANDATARANGECHECK-VAL
          IPMAPCANDATARANGECHECK
          IPMAPCANMISSINGMSG-VAL
          IPMAPCANMISSINGMSG
          VINSIGNALCOMPAREFAILURE-VAL
          VINSIGNALCOMPAREFAILURE
          MODULENOTCONFIGUREDERROR-VAL
          MODULENOTCONFIGUREDERROR
          CARCFGNOTCONFIGUREDERROR-VAL
          CARCFGNOTCONFIGUREDERROR
))