(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANSTOPFREQUENCYNRML-VAL
          CANSTOPFREQUENCYNRML
          CANPRPFACTORNRML-VAL
          CANPRPFACTORNRML
          CANDESIREDSWEEPBWNRML-VAL
          CANDESIREDSWEEPBWNRML
          CANRADIATIONCTRL-VAL
          CANRADIATIONCTRL
          CANSTOPFREQUENCYNRLL-VAL
          CANSTOPFREQUENCYNRLL
          CANPRPFACTORNRLL-VAL
          CANPRPFACTORNRLL
          CANDESIREDSWEEPBWNRLL-VAL
          CANDESIREDSWEEPBWNRLL
))