(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANSENSORPOLARITY-VAL
          CANSENSORPOLARITY
          CANSENSORLATOFFSET-VAL
          CANSENSORLATOFFSET
          CANSENSORLONGOFFSET-VAL
          CANSENSORLONGOFFSET
          CANSENSORHANGLEOFFSET-VAL
          CANSENSORHANGLEOFFSET
))