(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FSMYAWRATEVALID-VAL
          FSMYAWRATEVALID
          FSMYAWRATE-VAL
          FSMYAWRATE
          CANVEHICLEINDEX4FA-VAL
          CANVEHICLEINDEX4FA
          FSMVEHICLEVELOCITY-VAL
          FSMVEHICLEVELOCITY
          CANSTEERINGWHLANGLEQF-VAL
          CANSTEERINGWHLANGLEQF
          CANSTEERINGWHLANGLE-VAL
          CANSTEERINGWHLANGLE
))