(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANSERVALIGNUPDATESNEED-VAL
          CANSERVALIGNUPDATESNEED
          CANSERVALIGNTYPE-VAL
          CANSERVALIGNTYPE
          CANRADARHEIGHT-VAL
          CANRADARHEIGHT
          CANRADARFOVMR-VAL
          CANRADARFOVMR
          CANRADARFOVRR-VAL
          CANRADARFOVRR
          CANALIGNENABLE-VAL
          CANALIGNENABLE
          CANANGLEMOUNTINGHOFFSET-VAL
          CANANGLEMOUNTINGHOFFSET
          CANAALIGNAVGCTRTOTAL-VAL
          CANAALIGNAVGCTRTOTAL
))