(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          KRADARAZIMUTHPOLARITY-VAL
          KRADARAZIMUTHPOLARITY
          CANFAVERTGROUNDOFFSET-VAL
          CANFAVERTGROUNDOFFSET
          CANFAVERTLOWERLIMIT-VAL
          CANFAVERTLOWERLIMIT
          CANFAVERTUPPERLIMIT-VAL
          CANFAVERTUPPERLIMIT
          CANLROSCARCFGVEHTYPEFORD-VAL
          CANLROSCARCFGVEHTYPEFORD
          CANLROSCARCFGENGINEFORD-VAL
          CANLROSCARCFGENGINEFORD
))