(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANPBLFIELDREVISION-VAL
          CANPBLFIELDREVISION
          CANPBLPROMOTEREVISION-VAL
          CANPBLPROMOTEREVISION
          CANSWFIELDREVISION-VAL
          CANSWFIELDREVISION
          CANSWPROMOTEREVISION-VAL
          CANSWPROMOTEREVISION
          CANPBLRELEASEREVISION-VAL
          CANPBLRELEASEREVISION
))