(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANVEHICLESTAT-VAL
          CANVEHICLESTAT
          CANDAYNIGHTSTATUS-VAL
          CANDAYNIGHTSTATUS
          CANWIPERSTATUS-VAL
          CANWIPERSTATUS
          CANYAWRATEVALIDITY-VAL
          CANYAWRATEVALIDITY
          CANYAWRATE-VAL
          CANYAWRATE
          CANVEHICLESPEEDVALIDITY-VAL
          CANVEHICLESPEEDVALIDITY
          CANVEHICLESPEEDDIRECTION-VAL
          CANVEHICLESPEEDDIRECTION
          CANVEHICLESPEED-VAL
          CANVEHICLESPEED
))