(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MRRXCPCTORESPBYTE7-VAL
          MRRXCPCTORESPBYTE7
          MRRXCPCTORESPBYTE6-VAL
          MRRXCPCTORESPBYTE6
          MRRXCPCTORESPBYTE5-VAL
          MRRXCPCTORESPBYTE5
          MRRXCPCTORESPBYTE4-VAL
          MRRXCPCTORESPBYTE4
          MRRXCPCTORESPBYTE3-VAL
          MRRXCPCTORESPBYTE3
          MRRXCPCTORESPBYTE2-VAL
          MRRXCPCTORESPBYTE2
          MRRXCPCTORESPBYTE1-VAL
          MRRXCPCTORESPBYTE1
          MRRXCPCTORESPBYTE0-VAL
          MRRXCPCTORESPBYTE0
))