(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANMRRUPSIDEDOWN-VAL
          CANMRRUPSIDEDOWN
          CANBLOCKAGEFILTEROUTPUT-VAL
          CANBLOCKAGEFILTEROUTPUT
          CANANGLEMISALIGNMENTHDR-VAL
          CANANGLEMISALIGNMENTHDR
          CANUSEANGLEMISALIGNMENT-VAL
          CANUSEANGLEMISALIGNMENT
          CANBLOCKAGEDISABLE-VAL
          CANBLOCKAGEDISABLE
          CANSCANINDEXACK-VAL
          CANSCANINDEXACK
))