(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANAUTOALIGNHANGLEQF-VAL
          CANAUTOALIGNHANGLEQF
          CANALIGNMENTSTATUS-VAL
          CANALIGNMENTSTATUS
          CANALIGNMENTSTATE-VAL
          CANALIGNMENTSTATE
          CANAUTOALIGNHANGLEREF-VAL
          CANAUTOALIGNHANGLEREF
          CANAUTOALIGNHANGLE-VAL
          CANAUTOALIGNHANGLE
))