(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANSPEEDFRONTLEFTWHEEL-VAL
          CANSPEEDFRONTLEFTWHEEL
          CANSPEEDFRONTRIGHTWHEEL-VAL
          CANSPEEDFRONTRIGHTWHEEL
          CANSPEEDREARLEFTWHEEL-VAL
          CANSPEEDREARLEFTWHEEL
          CANSPEEDREARRIGHTWHEEL-VAL
          CANSPEEDREARRIGHTWHEEL
))