(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANPOWERSUPPFORD-VAL
          CANPOWERSUPPFORD
          CANPOWERMOTIVEFORD-VAL
          CANPOWERMOTIVEFORD
          CANCRUISESTATUSFORD-VAL
          CANCRUISESTATUSFORD
          CANVEHBATTVOLT-VAL
          CANVEHBATTVOLT
          CANGEARPOSITION-VAL
          CANGEARPOSITION
          CANAMBIENTTEMP-VAL
          CANAMBIENTTEMP
          CANIGNSTATUS-VAL
          CANIGNSTATUS
))