(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANFACTGTRANGER2M-VAL
          CANFACTGTRANGER2M
          CANFACTGTRANGEM2T-VAL
          CANFACTGTRANGEM2T
          CANFACTGTRANGE1-VAL
          CANFACTGTRANGE1
          CANFACTGTMTGSPACEHOR-VAL
          CANFACTGTMTGSPACEHOR
          CANFACTGTMTGOFFSET-VAL
          CANFACTGTMTGOFFSET
          CANFACALIGNSAMPREQ-VAL
          CANFACALIGNSAMPREQ
))