(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MRRXCPCTOCMDBYTE7-VAL
          MRRXCPCTOCMDBYTE7
          MRRXCPCTOCMDBYTE6-VAL
          MRRXCPCTOCMDBYTE6
          MRRXCPCTOCMDBYTE5-VAL
          MRRXCPCTOCMDBYTE5
          MRRXCPCTOCMDBYTE4-VAL
          MRRXCPCTOCMDBYTE4
          MRRXCPCTOCMDBYTE3-VAL
          MRRXCPCTOCMDBYTE3
          MRRXCPCTOCMDBYTE2-VAL
          MRRXCPCTOCMDBYTE2
          MRRXCPCTOCMDBYTE1-VAL
          MRRXCPCTOCMDBYTE1
          MRRXCPCTOCMDBYTE0-VAL
          MRRXCPCTOCMDBYTE0
))