(cl:in-package delphi_mrr_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CANLATERALMOUNTINGOFFSET-VAL
          CANLATERALMOUNTINGOFFSET
          CANFACPLATETILTNUMBER-VAL
          CANFACPLATETILTNUMBER
          CANFACPLATETILTANGLE-VAL
          CANFACPLATETILTANGLE
          CANFACPLATEPOSITIONSTOTAL-VAL
          CANFACPLATEPOSITIONSTOTAL
          CANFACALIGNMAXNT-VAL
          CANFACALIGNMAXNT
))