// Generated by gencpp from file ibeo_msgs/HostVehicleState2805.msg
// DO NOT EDIT!


#ifndef IBEO_MSGS_MESSAGE_HOSTVEHICLESTATE2805_H
#define IBEO_MSGS_MESSAGE_HOSTVEHICLESTATE2805_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ibeo_msgs/IbeoDataHeader.h>

namespace ibeo_msgs
{
template <class ContainerAllocator>
struct HostVehicleState2805_
{
  typedef HostVehicleState2805_<ContainerAllocator> Type;

  HostVehicleState2805_()
    : header()
    , ibeo_header()
    , timestamp()
    , scan_number(0)
    , error_flags(0)
    , longitudinal_velocity(0.0)
    , steering_wheel_angle(0.0)
    , front_wheel_angle(0.0)
    , x_position(0)
    , y_position(0)
    , course_angle(0)
    , time_difference(0)
    , x_difference(0)
    , y_difference(0)
    , heading_difference(0)
    , current_yaw_rate(0)  {
    }
  HostVehicleState2805_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ibeo_header(_alloc)
    , timestamp()
    , scan_number(0)
    , error_flags(0)
    , longitudinal_velocity(0.0)
    , steering_wheel_angle(0.0)
    , front_wheel_angle(0.0)
    , x_position(0)
    , y_position(0)
    , course_angle(0)
    , time_difference(0)
    , x_difference(0)
    , y_difference(0)
    , heading_difference(0)
    , current_yaw_rate(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::ibeo_msgs::IbeoDataHeader_<ContainerAllocator>  _ibeo_header_type;
  _ibeo_header_type ibeo_header;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint16_t _scan_number_type;
  _scan_number_type scan_number;

   typedef uint16_t _error_flags_type;
  _error_flags_type error_flags;

   typedef double _longitudinal_velocity_type;
  _longitudinal_velocity_type longitudinal_velocity;

   typedef double _steering_wheel_angle_type;
  _steering_wheel_angle_type steering_wheel_angle;

   typedef double _front_wheel_angle_type;
  _front_wheel_angle_type front_wheel_angle;

   typedef int32_t _x_position_type;
  _x_position_type x_position;

   typedef int32_t _y_position_type;
  _y_position_type y_position;

   typedef int16_t _course_angle_type;
  _course_angle_type course_angle;

   typedef uint16_t _time_difference_type;
  _time_difference_type time_difference;

   typedef int16_t _x_difference_type;
  _x_difference_type x_difference;

   typedef int16_t _y_difference_type;
  _y_difference_type y_difference;

   typedef int16_t _heading_difference_type;
  _heading_difference_type heading_difference;

   typedef int16_t _current_yaw_rate_type;
  _current_yaw_rate_type current_yaw_rate;





  typedef boost::shared_ptr< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> const> ConstPtr;

}; // struct HostVehicleState2805_

typedef ::ibeo_msgs::HostVehicleState2805_<std::allocator<void> > HostVehicleState2805;

typedef boost::shared_ptr< ::ibeo_msgs::HostVehicleState2805 > HostVehicleState2805Ptr;
typedef boost::shared_ptr< ::ibeo_msgs::HostVehicleState2805 const> HostVehicleState2805ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ibeo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'ibeo_msgs': ['/home/kratos/OFRN/catkin_ws/src/ibeo_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40f2e4a2b8baa9b2fbd2b34a1d0f47c9";
  }

  static const char* value(const ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40f2e4a2b8baa9b2ULL;
  static const uint64_t static_value2 = 0xfbd2b34a1d0f47c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibeo_msgs/HostVehicleState2805";
  }

  static const char* value(const ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
IbeoDataHeader ibeo_header\n\
time timestamp\n\
uint16 scan_number\n\
uint16 error_flags\n\
float64 longitudinal_velocity\n\
float64 steering_wheel_angle\n\
float64 front_wheel_angle\n\
int32 x_position\n\
int32 y_position\n\
int16 course_angle\n\
uint16 time_difference\n\
int16 x_difference\n\
int16 y_difference\n\
int16 heading_difference\n\
int16 current_yaw_rate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ibeo_msgs/IbeoDataHeader\n\
uint32 previous_message_size\n\
uint32 message_size\n\
uint8 device_id\n\
uint16 data_type_id\n\
time stamp\n\
";
  }

  static const char* value(const ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ibeo_header);
      stream.next(m.timestamp);
      stream.next(m.scan_number);
      stream.next(m.error_flags);
      stream.next(m.longitudinal_velocity);
      stream.next(m.steering_wheel_angle);
      stream.next(m.front_wheel_angle);
      stream.next(m.x_position);
      stream.next(m.y_position);
      stream.next(m.course_angle);
      stream.next(m.time_difference);
      stream.next(m.x_difference);
      stream.next(m.y_difference);
      stream.next(m.heading_difference);
      stream.next(m.current_yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HostVehicleState2805_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibeo_msgs::HostVehicleState2805_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ibeo_header: ";
    s << std::endl;
    Printer< ::ibeo_msgs::IbeoDataHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.ibeo_header);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "scan_number: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.scan_number);
    s << indent << "error_flags: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.error_flags);
    s << indent << "longitudinal_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.longitudinal_velocity);
    s << indent << "steering_wheel_angle: ";
    Printer<double>::stream(s, indent + "  ", v.steering_wheel_angle);
    s << indent << "front_wheel_angle: ";
    Printer<double>::stream(s, indent + "  ", v.front_wheel_angle);
    s << indent << "x_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_position);
    s << indent << "y_position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_position);
    s << indent << "course_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.course_angle);
    s << indent << "time_difference: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time_difference);
    s << indent << "x_difference: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_difference);
    s << indent << "y_difference: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_difference);
    s << indent << "heading_difference: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heading_difference);
    s << indent << "current_yaw_rate: ";
    Printer<int16_t>::stream(s, indent + "  ", v.current_yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBEO_MSGS_MESSAGE_HOSTVEHICLESTATE2805_H
