// Generated by gencpp from file ibeo_msgs/Sigma2D.msg
// DO NOT EDIT!


#ifndef IBEO_MSGS_MESSAGE_SIGMA2D_H
#define IBEO_MSGS_MESSAGE_SIGMA2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ibeo_msgs
{
template <class ContainerAllocator>
struct Sigma2D_
{
  typedef Sigma2D_<ContainerAllocator> Type;

  Sigma2D_()
    : sigma_x(0)
    , sigma_y(0)  {
    }
  Sigma2D_(const ContainerAllocator& _alloc)
    : sigma_x(0)
    , sigma_y(0)  {
  (void)_alloc;
    }



   typedef uint16_t _sigma_x_type;
  _sigma_x_type sigma_x;

   typedef uint16_t _sigma_y_type;
  _sigma_y_type sigma_y;





  typedef boost::shared_ptr< ::ibeo_msgs::Sigma2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibeo_msgs::Sigma2D_<ContainerAllocator> const> ConstPtr;

}; // struct Sigma2D_

typedef ::ibeo_msgs::Sigma2D_<std::allocator<void> > Sigma2D;

typedef boost::shared_ptr< ::ibeo_msgs::Sigma2D > Sigma2DPtr;
typedef boost::shared_ptr< ::ibeo_msgs::Sigma2D const> Sigma2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibeo_msgs::Sigma2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ibeo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ibeo_msgs': ['/home/kratos/OFRN/catkin_ws/src/ibeo_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibeo_msgs::Sigma2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibeo_msgs::Sigma2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibeo_msgs::Sigma2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea0a3ef73a6d156e4c33f644431f6d77";
  }

  static const char* value(const ::ibeo_msgs::Sigma2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea0a3ef73a6d156eULL;
  static const uint64_t static_value2 = 0x4c33f644431f6d77ULL;
};

template<class ContainerAllocator>
struct DataType< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibeo_msgs/Sigma2D";
  }

  static const char* value(const ::ibeo_msgs::Sigma2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 sigma_x\n\
uint16 sigma_y\n\
";
  }

  static const char* value(const ::ibeo_msgs::Sigma2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sigma_x);
      stream.next(m.sigma_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sigma2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibeo_msgs::Sigma2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibeo_msgs::Sigma2D_<ContainerAllocator>& v)
  {
    s << indent << "sigma_x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sigma_x);
    s << indent << "sigma_y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sigma_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBEO_MSGS_MESSAGE_SIGMA2D_H
