// Generated by gencpp from file ibeo_msgs/UntrackedProperties.msg
// DO NOT EDIT!


#ifndef IBEO_MSGS_MESSAGE_UNTRACKEDPROPERTIES_H
#define IBEO_MSGS_MESSAGE_UNTRACKEDPROPERTIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ibeo_msgs/Point2Di.h>
#include <ibeo_msgs/Point2Di.h>
#include <ibeo_msgs/Point2Dui.h>
#include <ibeo_msgs/Point2Di.h>
#include <ibeo_msgs/Point2Dui.h>
#include <ibeo_msgs/ContourPointSigma.h>

namespace ibeo_msgs
{
template <class ContainerAllocator>
struct UntrackedProperties_
{
  typedef UntrackedProperties_<ContainerAllocator> Type;

  UntrackedProperties_()
    : relative_time_of_measurement(0)
    , position_closest_point()
    , object_box_size()
    , object_box_size_sigma()
    , object_box_orientation(0)
    , object_box_orientation_sigma(0)
    , tracking_point_coordinate()
    , tracking_point_coordinate_sigma()
    , number_of_contour_points(0)
    , contour_point_list()  {
    }
  UntrackedProperties_(const ContainerAllocator& _alloc)
    : relative_time_of_measurement(0)
    , position_closest_point(_alloc)
    , object_box_size(_alloc)
    , object_box_size_sigma(_alloc)
    , object_box_orientation(0)
    , object_box_orientation_sigma(0)
    , tracking_point_coordinate(_alloc)
    , tracking_point_coordinate_sigma(_alloc)
    , number_of_contour_points(0)
    , contour_point_list(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _relative_time_of_measurement_type;
  _relative_time_of_measurement_type relative_time_of_measurement;

   typedef  ::ibeo_msgs::Point2Di_<ContainerAllocator>  _position_closest_point_type;
  _position_closest_point_type position_closest_point;

   typedef  ::ibeo_msgs::Point2Di_<ContainerAllocator>  _object_box_size_type;
  _object_box_size_type object_box_size;

   typedef  ::ibeo_msgs::Point2Dui_<ContainerAllocator>  _object_box_size_sigma_type;
  _object_box_size_sigma_type object_box_size_sigma;

   typedef int16_t _object_box_orientation_type;
  _object_box_orientation_type object_box_orientation;

   typedef uint16_t _object_box_orientation_sigma_type;
  _object_box_orientation_sigma_type object_box_orientation_sigma;

   typedef  ::ibeo_msgs::Point2Di_<ContainerAllocator>  _tracking_point_coordinate_type;
  _tracking_point_coordinate_type tracking_point_coordinate;

   typedef  ::ibeo_msgs::Point2Dui_<ContainerAllocator>  _tracking_point_coordinate_sigma_type;
  _tracking_point_coordinate_sigma_type tracking_point_coordinate_sigma;

   typedef uint8_t _number_of_contour_points_type;
  _number_of_contour_points_type number_of_contour_points;

   typedef std::vector< ::ibeo_msgs::ContourPointSigma_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ibeo_msgs::ContourPointSigma_<ContainerAllocator> >::other >  _contour_point_list_type;
  _contour_point_list_type contour_point_list;





  typedef boost::shared_ptr< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> const> ConstPtr;

}; // struct UntrackedProperties_

typedef ::ibeo_msgs::UntrackedProperties_<std::allocator<void> > UntrackedProperties;

typedef boost::shared_ptr< ::ibeo_msgs::UntrackedProperties > UntrackedPropertiesPtr;
typedef boost::shared_ptr< ::ibeo_msgs::UntrackedProperties const> UntrackedPropertiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ibeo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ibeo_msgs': ['/home/kratos/OFRN/catkin_ws/src/ibeo_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec203d9d51180705332e0238e3e4abda";
  }

  static const char* value(const ::ibeo_msgs::UntrackedProperties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec203d9d51180705ULL;
  static const uint64_t static_value2 = 0x332e0238e3e4abdaULL;
};

template<class ContainerAllocator>
struct DataType< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibeo_msgs/UntrackedProperties";
  }

  static const char* value(const ::ibeo_msgs::UntrackedProperties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 relative_time_of_measurement\n\
Point2Di position_closest_point\n\
Point2Di object_box_size\n\
Point2Dui object_box_size_sigma\n\
int16 object_box_orientation\n\
uint16 object_box_orientation_sigma\n\
Point2Di tracking_point_coordinate\n\
Point2Dui tracking_point_coordinate_sigma\n\
uint8 number_of_contour_points\n\
ContourPointSigma[] contour_point_list\n\
\n\
================================================================================\n\
MSG: ibeo_msgs/Point2Di\n\
int16 x\n\
int16 y\n\
\n\
================================================================================\n\
MSG: ibeo_msgs/Point2Dui\n\
uint16 x\n\
uint16 y\n\
\n\
================================================================================\n\
MSG: ibeo_msgs/ContourPointSigma\n\
int16 x\n\
int16 y\n\
uint8 x_sigma\n\
uint8 y_sigma\n\
";
  }

  static const char* value(const ::ibeo_msgs::UntrackedProperties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.relative_time_of_measurement);
      stream.next(m.position_closest_point);
      stream.next(m.object_box_size);
      stream.next(m.object_box_size_sigma);
      stream.next(m.object_box_orientation);
      stream.next(m.object_box_orientation_sigma);
      stream.next(m.tracking_point_coordinate);
      stream.next(m.tracking_point_coordinate_sigma);
      stream.next(m.number_of_contour_points);
      stream.next(m.contour_point_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UntrackedProperties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibeo_msgs::UntrackedProperties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibeo_msgs::UntrackedProperties_<ContainerAllocator>& v)
  {
    s << indent << "relative_time_of_measurement: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.relative_time_of_measurement);
    s << indent << "position_closest_point: ";
    s << std::endl;
    Printer< ::ibeo_msgs::Point2Di_<ContainerAllocator> >::stream(s, indent + "  ", v.position_closest_point);
    s << indent << "object_box_size: ";
    s << std::endl;
    Printer< ::ibeo_msgs::Point2Di_<ContainerAllocator> >::stream(s, indent + "  ", v.object_box_size);
    s << indent << "object_box_size_sigma: ";
    s << std::endl;
    Printer< ::ibeo_msgs::Point2Dui_<ContainerAllocator> >::stream(s, indent + "  ", v.object_box_size_sigma);
    s << indent << "object_box_orientation: ";
    Printer<int16_t>::stream(s, indent + "  ", v.object_box_orientation);
    s << indent << "object_box_orientation_sigma: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object_box_orientation_sigma);
    s << indent << "tracking_point_coordinate: ";
    s << std::endl;
    Printer< ::ibeo_msgs::Point2Di_<ContainerAllocator> >::stream(s, indent + "  ", v.tracking_point_coordinate);
    s << indent << "tracking_point_coordinate_sigma: ";
    s << std::endl;
    Printer< ::ibeo_msgs::Point2Dui_<ContainerAllocator> >::stream(s, indent + "  ", v.tracking_point_coordinate_sigma);
    s << indent << "number_of_contour_points: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number_of_contour_points);
    s << indent << "contour_point_list[]" << std::endl;
    for (size_t i = 0; i < v.contour_point_list.size(); ++i)
    {
      s << indent << "  contour_point_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ibeo_msgs::ContourPointSigma_<ContainerAllocator> >::stream(s, indent + "    ", v.contour_point_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBEO_MSGS_MESSAGE_UNTRACKEDPROPERTIES_H
