(cl:defpackage automotive_navigation_msgs-srv
  (:use )
  (:export
   "GETIMAGEFORMAPTILE"
   "<GETIMAGEFORMAPTILE-REQUEST>"
   "GETIMAGEFORMAPTILE-REQUEST"
   "<GETIMAGEFORMAPTILE-RESPONSE>"
   "GETIMAGEFORMAPTILE-RESPONSE"
  ))

