# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_srr_msgs/SrrStatus4.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SrrStatus4(genpy.Message):
  _md5sum = "5888431f2fe93e9b1c17ca7520274fa9"
  _type = "delphi_srr_msgs/SrrStatus4"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Message file for srr_status4

Header header

uint16    CAN_TX_SW_VERSION_HOST                  

uint8     CAN_TX_PATH_ID_BLIS_IGNORE              

uint8     CAN_TX_PATH_ID_BLIS                     

float32   CAN_TX_ANGLE_MISALIGNMENT               

float32   CAN_TX_AUTO_ALIGN_ANGLE                 


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','CAN_TX_SW_VERSION_HOST','CAN_TX_PATH_ID_BLIS_IGNORE','CAN_TX_PATH_ID_BLIS','CAN_TX_ANGLE_MISALIGNMENT','CAN_TX_AUTO_ALIGN_ANGLE']
  _slot_types = ['std_msgs/Header','uint16','uint8','uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,CAN_TX_SW_VERSION_HOST,CAN_TX_PATH_ID_BLIS_IGNORE,CAN_TX_PATH_ID_BLIS,CAN_TX_ANGLE_MISALIGNMENT,CAN_TX_AUTO_ALIGN_ANGLE

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SrrStatus4, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.CAN_TX_SW_VERSION_HOST is None:
        self.CAN_TX_SW_VERSION_HOST = 0
      if self.CAN_TX_PATH_ID_BLIS_IGNORE is None:
        self.CAN_TX_PATH_ID_BLIS_IGNORE = 0
      if self.CAN_TX_PATH_ID_BLIS is None:
        self.CAN_TX_PATH_ID_BLIS = 0
      if self.CAN_TX_ANGLE_MISALIGNMENT is None:
        self.CAN_TX_ANGLE_MISALIGNMENT = 0.
      if self.CAN_TX_AUTO_ALIGN_ANGLE is None:
        self.CAN_TX_AUTO_ALIGN_ANGLE = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.CAN_TX_SW_VERSION_HOST = 0
      self.CAN_TX_PATH_ID_BLIS_IGNORE = 0
      self.CAN_TX_PATH_ID_BLIS = 0
      self.CAN_TX_ANGLE_MISALIGNMENT = 0.
      self.CAN_TX_AUTO_ALIGN_ANGLE = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_H2B2f().pack(_x.CAN_TX_SW_VERSION_HOST, _x.CAN_TX_PATH_ID_BLIS_IGNORE, _x.CAN_TX_PATH_ID_BLIS, _x.CAN_TX_ANGLE_MISALIGNMENT, _x.CAN_TX_AUTO_ALIGN_ANGLE))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.CAN_TX_SW_VERSION_HOST, _x.CAN_TX_PATH_ID_BLIS_IGNORE, _x.CAN_TX_PATH_ID_BLIS, _x.CAN_TX_ANGLE_MISALIGNMENT, _x.CAN_TX_AUTO_ALIGN_ANGLE,) = _get_struct_H2B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_H2B2f().pack(_x.CAN_TX_SW_VERSION_HOST, _x.CAN_TX_PATH_ID_BLIS_IGNORE, _x.CAN_TX_PATH_ID_BLIS, _x.CAN_TX_ANGLE_MISALIGNMENT, _x.CAN_TX_AUTO_ALIGN_ANGLE))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.CAN_TX_SW_VERSION_HOST, _x.CAN_TX_PATH_ID_BLIS_IGNORE, _x.CAN_TX_PATH_ID_BLIS, _x.CAN_TX_ANGLE_MISALIGNMENT, _x.CAN_TX_AUTO_ALIGN_ANGLE,) = _get_struct_H2B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H2B2f = None
def _get_struct_H2B2f():
    global _struct_H2B2f
    if _struct_H2B2f is None:
        _struct_H2B2f = struct.Struct("<H2B2f")
    return _struct_H2B2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
