// Generated by gencpp from file neobotix_usboard_msgs/AnsWriteParaset.msg
// DO NOT EDIT!


#ifndef NEOBOTIX_USBOARD_MSGS_MESSAGE_ANSWRITEPARASET_H
#define NEOBOTIX_USBOARD_MSGS_MESSAGE_ANSWRITEPARASET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neobotix_usboard_msgs
{
template <class ContainerAllocator>
struct AnsWriteParaset_
{
  typedef AnsWriteParaset_<ContainerAllocator> Type;

  AnsWriteParaset_()
    : header()
    , command(0)
    , paramset_cksum_low_byte(0)
    , paramset_cksum_high_byte(0)  {
    }
  AnsWriteParaset_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(0)
    , paramset_cksum_low_byte(0)
    , paramset_cksum_high_byte(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _command_type;
  _command_type command;

   typedef uint8_t _paramset_cksum_low_byte_type;
  _paramset_cksum_low_byte_type paramset_cksum_low_byte;

   typedef uint8_t _paramset_cksum_high_byte_type;
  _paramset_cksum_high_byte_type paramset_cksum_high_byte;





  typedef boost::shared_ptr< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> const> ConstPtr;

}; // struct AnsWriteParaset_

typedef ::neobotix_usboard_msgs::AnsWriteParaset_<std::allocator<void> > AnsWriteParaset;

typedef boost::shared_ptr< ::neobotix_usboard_msgs::AnsWriteParaset > AnsWriteParasetPtr;
typedef boost::shared_ptr< ::neobotix_usboard_msgs::AnsWriteParaset const> AnsWriteParasetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neobotix_usboard_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'neobotix_usboard_msgs': ['/home/kratos/OFRN/catkin_ws/src/neobotix_usboard_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73cd7b344457ad8ea263f2b6c0b90b01";
  }

  static const char* value(const ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73cd7b344457ad8eULL;
  static const uint64_t static_value2 = 0xa263f2b6c0b90b01ULL;
};

template<class ContainerAllocator>
struct DataType< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neobotix_usboard_msgs/AnsWriteParaset";
  }

  static const char* value(const ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message file for AnsWriteParaset\n\
\n\
Header header\n\
\n\
uint8     command                                 \n\
\n\
uint8     paramset_cksum_low_byte                  \n\
\n\
uint8     paramset_cksum_high_byte                 \n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
      stream.next(m.paramset_cksum_low_byte);
      stream.next(m.paramset_cksum_high_byte);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnsWriteParaset_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neobotix_usboard_msgs::AnsWriteParaset_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "paramset_cksum_low_byte: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paramset_cksum_low_byte);
    s << indent << "paramset_cksum_high_byte: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paramset_cksum_high_byte);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEOBOTIX_USBOARD_MSGS_MESSAGE_ANSWRITEPARASET_H
