// Generated by gencpp from file delphi_mrr_msgs/ActiveFaultLatched2.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_ACTIVEFAULTLATCHED2_H
#define DELPHI_MRR_MSGS_MESSAGE_ACTIVEFAULTLATCHED2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct ActiveFaultLatched2_
{
  typedef ActiveFaultLatched2_<ContainerAllocator> Type;

  ActiveFaultLatched2_()
    : header()
    , ipmaPcanDataRangeCheck(false)
    , ipmaPcanMissingMsg(false)
    , vinSignalCompareFailure(false)
    , moduleNotConfiguredError(false)
    , carcfgNotConfiguredError(false)  {
    }
  ActiveFaultLatched2_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ipmaPcanDataRangeCheck(false)
    , ipmaPcanMissingMsg(false)
    , vinSignalCompareFailure(false)
    , moduleNotConfiguredError(false)
    , carcfgNotConfiguredError(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ipmaPcanDataRangeCheck_type;
  _ipmaPcanDataRangeCheck_type ipmaPcanDataRangeCheck;

   typedef uint8_t _ipmaPcanMissingMsg_type;
  _ipmaPcanMissingMsg_type ipmaPcanMissingMsg;

   typedef uint8_t _vinSignalCompareFailure_type;
  _vinSignalCompareFailure_type vinSignalCompareFailure;

   typedef uint8_t _moduleNotConfiguredError_type;
  _moduleNotConfiguredError_type moduleNotConfiguredError;

   typedef uint8_t _carcfgNotConfiguredError_type;
  _carcfgNotConfiguredError_type carcfgNotConfiguredError;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> const> ConstPtr;

}; // struct ActiveFaultLatched2_

typedef ::delphi_mrr_msgs::ActiveFaultLatched2_<std::allocator<void> > ActiveFaultLatched2;

typedef boost::shared_ptr< ::delphi_mrr_msgs::ActiveFaultLatched2 > ActiveFaultLatched2Ptr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::ActiveFaultLatched2 const> ActiveFaultLatched2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f38927c1ce159d73ec22ce267eded9a9";
  }

  static const char* value(const ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf38927c1ce159d73ULL;
  static const uint64_t static_value2 = 0xec22ce267eded9a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/ActiveFaultLatched2";
  }

  static const char* value(const ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
bool ipmaPcanDataRangeCheck\n\
bool ipmaPcanMissingMsg\n\
bool vinSignalCompareFailure\n\
bool moduleNotConfiguredError\n\
bool carcfgNotConfiguredError\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ipmaPcanDataRangeCheck);
      stream.next(m.ipmaPcanMissingMsg);
      stream.next(m.vinSignalCompareFailure);
      stream.next(m.moduleNotConfiguredError);
      stream.next(m.carcfgNotConfiguredError);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActiveFaultLatched2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::ActiveFaultLatched2_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ipmaPcanDataRangeCheck: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ipmaPcanDataRangeCheck);
    s << indent << "ipmaPcanMissingMsg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ipmaPcanMissingMsg);
    s << indent << "vinSignalCompareFailure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vinSignalCompareFailure);
    s << indent << "moduleNotConfiguredError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moduleNotConfiguredError);
    s << indent << "carcfgNotConfiguredError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carcfgNotConfiguredError);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_ACTIVEFAULTLATCHED2_H
