// Generated by gencpp from file delphi_mrr_msgs/LrosSignalsActualValues.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_LROSSIGNALSACTUALVALUES_H
#define DELPHI_MRR_MSGS_MESSAGE_LROSSIGNALSACTUALVALUES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct LrosSignalsActualValues_
{
  typedef LrosSignalsActualValues_<ContainerAllocator> Type;

  LrosSignalsActualValues_()
    : header()
    , canPowerSuppFord(0)
    , canPowerMotiveFord(0)
    , canCruiseStatusFord(0.0)
    , canVehBattVolt(0)
    , canGearPosition(0)
    , canAmbientTemp(0.0)
    , canIgnStatus(0)  {
    }
  LrosSignalsActualValues_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canPowerSuppFord(0)
    , canPowerMotiveFord(0)
    , canCruiseStatusFord(0.0)
    , canVehBattVolt(0)
    , canGearPosition(0)
    , canAmbientTemp(0.0)
    , canIgnStatus(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _canPowerSuppFord_type;
  _canPowerSuppFord_type canPowerSuppFord;

   typedef uint8_t _canPowerMotiveFord_type;
  _canPowerMotiveFord_type canPowerMotiveFord;

   typedef float _canCruiseStatusFord_type;
  _canCruiseStatusFord_type canCruiseStatusFord;

   typedef uint8_t _canVehBattVolt_type;
  _canVehBattVolt_type canVehBattVolt;

   typedef uint16_t _canGearPosition_type;
  _canGearPosition_type canGearPosition;

   typedef float _canAmbientTemp_type;
  _canAmbientTemp_type canAmbientTemp;

   typedef uint8_t _canIgnStatus_type;
  _canIgnStatus_type canIgnStatus;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const> ConstPtr;

}; // struct LrosSignalsActualValues_

typedef ::delphi_mrr_msgs::LrosSignalsActualValues_<std::allocator<void> > LrosSignalsActualValues;

typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues > LrosSignalsActualValuesPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::LrosSignalsActualValues const> LrosSignalsActualValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e964d7b51372521395c914dc44defcb7";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe964d7b513725213ULL;
  static const uint64_t static_value2 = 0x95c914dc44defcb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/LrosSignalsActualValues";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 	canPowerSuppFord\n\
uint8 	canPowerMotiveFord\n\
float32   canCruiseStatusFord\n\
uint8 	canVehBattVolt\n\
uint16 	canGearPosition\n\
float32   canAmbientTemp\n\
uint8 	canIgnStatus\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canPowerSuppFord);
      stream.next(m.canPowerMotiveFord);
      stream.next(m.canCruiseStatusFord);
      stream.next(m.canVehBattVolt);
      stream.next(m.canGearPosition);
      stream.next(m.canAmbientTemp);
      stream.next(m.canIgnStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LrosSignalsActualValues_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::LrosSignalsActualValues_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canPowerSuppFord: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canPowerSuppFord);
    s << indent << "canPowerMotiveFord: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canPowerMotiveFord);
    s << indent << "canCruiseStatusFord: ";
    Printer<float>::stream(s, indent + "  ", v.canCruiseStatusFord);
    s << indent << "canVehBattVolt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canVehBattVolt);
    s << indent << "canGearPosition: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.canGearPosition);
    s << indent << "canAmbientTemp: ";
    Printer<float>::stream(s, indent + "  ", v.canAmbientTemp);
    s << indent << "canIgnStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canIgnStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_LROSSIGNALSACTUALVALUES_H
