// Generated by gencpp from file delphi_mrr_msgs/MrrStatusSwVersion.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_MRRSTATUSSWVERSION_H
#define DELPHI_MRR_MSGS_MESSAGE_MRRSTATUSSWVERSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct MrrStatusSwVersion_
{
  typedef MrrStatusSwVersion_<ContainerAllocator> Type;

  MrrStatusSwVersion_()
    : header()
    , canPblFieldRevision(0)
    , canPblPromoteRevision(0)
    , canSwFieldRevision(0)
    , canSwPromoteRevision(0)
    , canPblReleaseRevision(0)  {
    }
  MrrStatusSwVersion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canPblFieldRevision(0)
    , canPblPromoteRevision(0)
    , canSwFieldRevision(0)
    , canSwPromoteRevision(0)
    , canPblReleaseRevision(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _canPblFieldRevision_type;
  _canPblFieldRevision_type canPblFieldRevision;

   typedef uint8_t _canPblPromoteRevision_type;
  _canPblPromoteRevision_type canPblPromoteRevision;

   typedef uint8_t _canSwFieldRevision_type;
  _canSwFieldRevision_type canSwFieldRevision;

   typedef uint8_t _canSwPromoteRevision_type;
  _canSwPromoteRevision_type canSwPromoteRevision;

   typedef uint8_t _canPblReleaseRevision_type;
  _canPblReleaseRevision_type canPblReleaseRevision;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> const> ConstPtr;

}; // struct MrrStatusSwVersion_

typedef ::delphi_mrr_msgs::MrrStatusSwVersion_<std::allocator<void> > MrrStatusSwVersion;

typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrStatusSwVersion > MrrStatusSwVersionPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::MrrStatusSwVersion const> MrrStatusSwVersionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2c73687f2bc68d73e5cd6ce7c58eb34";
  }

  static const char* value(const ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2c73687f2bc68d7ULL;
  static const uint64_t static_value2 = 0x3e5cd6ce7c58eb34ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/MrrStatusSwVersion";
  }

  static const char* value(const ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 canPblFieldRevision\n\
uint8 canPblPromoteRevision \n\
uint8 canSwFieldRevision\n\
uint8 canSwPromoteRevision\n\
uint8 canPblReleaseRevision\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canPblFieldRevision);
      stream.next(m.canPblPromoteRevision);
      stream.next(m.canSwFieldRevision);
      stream.next(m.canSwPromoteRevision);
      stream.next(m.canPblReleaseRevision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MrrStatusSwVersion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::MrrStatusSwVersion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canPblFieldRevision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canPblFieldRevision);
    s << indent << "canPblPromoteRevision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canPblPromoteRevision);
    s << indent << "canSwFieldRevision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canSwFieldRevision);
    s << indent << "canSwPromoteRevision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canSwPromoteRevision);
    s << indent << "canPblReleaseRevision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canPblReleaseRevision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_MRRSTATUSSWVERSION_H
