// Generated by gencpp from file delphi_mrr_msgs/SystemStatus.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_SYSTEMSTATUS_H
#define DELPHI_MRR_MSGS_MESSAGE_SYSTEMSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct SystemStatus_
{
  typedef SystemStatus_<ContainerAllocator> Type;

  SystemStatus_()
    : header()
    , canVehicleStat(false)
    , canDayNightStatus(false)
    , canWiperStatus(false)
    , canYawRateValidity(false)
    , canYawRate(0.0)
    , canVehicleSpeedValidity(false)
    , canVehicleSpeedDirection(false)
    , canVehicleSpeed(0.0)  {
    }
  SystemStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canVehicleStat(false)
    , canDayNightStatus(false)
    , canWiperStatus(false)
    , canYawRateValidity(false)
    , canYawRate(0.0)
    , canVehicleSpeedValidity(false)
    , canVehicleSpeedDirection(false)
    , canVehicleSpeed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _canVehicleStat_type;
  _canVehicleStat_type canVehicleStat;

   typedef uint8_t _canDayNightStatus_type;
  _canDayNightStatus_type canDayNightStatus;

   typedef uint8_t _canWiperStatus_type;
  _canWiperStatus_type canWiperStatus;

   typedef uint8_t _canYawRateValidity_type;
  _canYawRateValidity_type canYawRateValidity;

   typedef float _canYawRate_type;
  _canYawRate_type canYawRate;

   typedef uint8_t _canVehicleSpeedValidity_type;
  _canVehicleSpeedValidity_type canVehicleSpeedValidity;

   typedef uint8_t _canVehicleSpeedDirection_type;
  _canVehicleSpeedDirection_type canVehicleSpeedDirection;

   typedef float _canVehicleSpeed_type;
  _canVehicleSpeed_type canVehicleSpeed;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatus_

typedef ::delphi_mrr_msgs::SystemStatus_<std::allocator<void> > SystemStatus;

typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus > SystemStatusPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::SystemStatus const> SystemStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a90f59e9f02310b21c177ed8eddac12a";
  }

  static const char* value(const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa90f59e9f02310b2ULL;
  static const uint64_t static_value2 = 0x1c177ed8eddac12aULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/SystemStatus";
  }

  static const char* value(const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
bool 	canVehicleStat\n\
bool 	canDayNightStatus\n\
bool 	canWiperStatus\n\
bool 	canYawRateValidity\n\
float32 	canYawRate\n\
bool 	canVehicleSpeedValidity\n\
bool 	canVehicleSpeedDirection\n\
float32 	canVehicleSpeed\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canVehicleStat);
      stream.next(m.canDayNightStatus);
      stream.next(m.canWiperStatus);
      stream.next(m.canYawRateValidity);
      stream.next(m.canYawRate);
      stream.next(m.canVehicleSpeedValidity);
      stream.next(m.canVehicleSpeedDirection);
      stream.next(m.canVehicleSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::SystemStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canVehicleStat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canVehicleStat);
    s << indent << "canDayNightStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canDayNightStatus);
    s << indent << "canWiperStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canWiperStatus);
    s << indent << "canYawRateValidity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canYawRateValidity);
    s << indent << "canYawRate: ";
    Printer<float>::stream(s, indent + "  ", v.canYawRate);
    s << indent << "canVehicleSpeedValidity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canVehicleSpeedValidity);
    s << indent << "canVehicleSpeedDirection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.canVehicleSpeedDirection);
    s << indent << "canVehicleSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.canVehicleSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_SYSTEMSTATUS_H
