// Generated by gencpp from file delphi_mrr_msgs/TrackMotionPower.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_TRACKMOTIONPOWER_H
#define DELPHI_MRR_MSGS_MESSAGE_TRACKMOTIONPOWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct TrackMotionPower_
{
  typedef TrackMotionPower_<ContainerAllocator> Type;

  TrackMotionPower_()
    : header()
    , movableFast(false)
    , movableSlow(false)
    , moving(false)
    , power(0)  {
    }
  TrackMotionPower_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , movableFast(false)
    , movableSlow(false)
    , moving(false)
    , power(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _movableFast_type;
  _movableFast_type movableFast;

   typedef uint8_t _movableSlow_type;
  _movableSlow_type movableSlow;

   typedef uint8_t _moving_type;
  _moving_type moving;

   typedef int8_t _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> const> ConstPtr;

}; // struct TrackMotionPower_

typedef ::delphi_mrr_msgs::TrackMotionPower_<std::allocator<void> > TrackMotionPower;

typedef boost::shared_ptr< ::delphi_mrr_msgs::TrackMotionPower > TrackMotionPowerPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::TrackMotionPower const> TrackMotionPowerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60d9d46dbc2553e20af8f241eeeae906";
  }

  static const char* value(const ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60d9d46dbc2553e2ULL;
  static const uint64_t static_value2 = 0x0af8f241eeeae906ULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/TrackMotionPower";
  }

  static const char* value(const ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
\n\
bool  movableFast\n\
bool  movableSlow\n\
bool  moving\n\
int8 power\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.movableFast);
      stream.next(m.movableSlow);
      stream.next(m.moving);
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackMotionPower_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::TrackMotionPower_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "movableFast: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.movableFast);
    s << indent << "movableSlow: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.movableSlow);
    s << indent << "moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moving);
    s << indent << "power: ";
    Printer<int8_t>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_TRACKMOTIONPOWER_H
