// Generated by gencpp from file delphi_mrr_msgs/XCPMrrDaqResp.msg
// DO NOT EDIT!


#ifndef DELPHI_MRR_MSGS_MESSAGE_XCPMRRDAQRESP_H
#define DELPHI_MRR_MSGS_MESSAGE_XCPMRRDAQRESP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace delphi_mrr_msgs
{
template <class ContainerAllocator>
struct XCPMrrDaqResp_
{
  typedef XCPMrrDaqResp_<ContainerAllocator> Type;

  XCPMrrDaqResp_()
    : header()
    , mrrXcpDaqRespByte7(0)
    , mrrXcpDaqRespByte6(0)
    , mrrXcpDaqRespByte5(0)
    , mrrXcpDaqRespByte4(0)
    , mrrXcpDaqRespByte3(0)
    , mrrXcpDaqRespByte2(0)
    , mrrXcpDaqRespByte1(0)
    , mrrXcpDaqRespByte0(0)  {
    }
  XCPMrrDaqResp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mrrXcpDaqRespByte7(0)
    , mrrXcpDaqRespByte6(0)
    , mrrXcpDaqRespByte5(0)
    , mrrXcpDaqRespByte4(0)
    , mrrXcpDaqRespByte3(0)
    , mrrXcpDaqRespByte2(0)
    , mrrXcpDaqRespByte1(0)
    , mrrXcpDaqRespByte0(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mrrXcpDaqRespByte7_type;
  _mrrXcpDaqRespByte7_type mrrXcpDaqRespByte7;

   typedef uint8_t _mrrXcpDaqRespByte6_type;
  _mrrXcpDaqRespByte6_type mrrXcpDaqRespByte6;

   typedef uint8_t _mrrXcpDaqRespByte5_type;
  _mrrXcpDaqRespByte5_type mrrXcpDaqRespByte5;

   typedef uint8_t _mrrXcpDaqRespByte4_type;
  _mrrXcpDaqRespByte4_type mrrXcpDaqRespByte4;

   typedef uint8_t _mrrXcpDaqRespByte3_type;
  _mrrXcpDaqRespByte3_type mrrXcpDaqRespByte3;

   typedef uint8_t _mrrXcpDaqRespByte2_type;
  _mrrXcpDaqRespByte2_type mrrXcpDaqRespByte2;

   typedef uint8_t _mrrXcpDaqRespByte1_type;
  _mrrXcpDaqRespByte1_type mrrXcpDaqRespByte1;

   typedef uint8_t _mrrXcpDaqRespByte0_type;
  _mrrXcpDaqRespByte0_type mrrXcpDaqRespByte0;





  typedef boost::shared_ptr< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> const> ConstPtr;

}; // struct XCPMrrDaqResp_

typedef ::delphi_mrr_msgs::XCPMrrDaqResp_<std::allocator<void> > XCPMrrDaqResp;

typedef boost::shared_ptr< ::delphi_mrr_msgs::XCPMrrDaqResp > XCPMrrDaqRespPtr;
typedef boost::shared_ptr< ::delphi_mrr_msgs::XCPMrrDaqResp const> XCPMrrDaqRespConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delphi_mrr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delphi_mrr_msgs': ['/home/kratos/OFRN/catkin_ws/src/delphi_mrr_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "138663684e1e7548f26a639edd69539b";
  }

  static const char* value(const ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x138663684e1e7548ULL;
  static const uint64_t static_value2 = 0xf26a639edd69539bULL;
};

template<class ContainerAllocator>
struct DataType< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delphi_mrr_msgs/XCPMrrDaqResp";
  }

  static const char* value(const ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 mrrXcpDaqRespByte7\n\
uint8 mrrXcpDaqRespByte6\n\
uint8 mrrXcpDaqRespByte5\n\
uint8 mrrXcpDaqRespByte4\n\
uint8 mrrXcpDaqRespByte3\n\
uint8 mrrXcpDaqRespByte2\n\
uint8 mrrXcpDaqRespByte1\n\
uint8 mrrXcpDaqRespByte0\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mrrXcpDaqRespByte7);
      stream.next(m.mrrXcpDaqRespByte6);
      stream.next(m.mrrXcpDaqRespByte5);
      stream.next(m.mrrXcpDaqRespByte4);
      stream.next(m.mrrXcpDaqRespByte3);
      stream.next(m.mrrXcpDaqRespByte2);
      stream.next(m.mrrXcpDaqRespByte1);
      stream.next(m.mrrXcpDaqRespByte0);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XCPMrrDaqResp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delphi_mrr_msgs::XCPMrrDaqResp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mrrXcpDaqRespByte7: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte7);
    s << indent << "mrrXcpDaqRespByte6: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte6);
    s << indent << "mrrXcpDaqRespByte5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte5);
    s << indent << "mrrXcpDaqRespByte4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte4);
    s << indent << "mrrXcpDaqRespByte3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte3);
    s << indent << "mrrXcpDaqRespByte2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte2);
    s << indent << "mrrXcpDaqRespByte1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte1);
    s << indent << "mrrXcpDaqRespByte0: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mrrXcpDaqRespByte0);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELPHI_MRR_MSGS_MESSAGE_XCPMRRDAQRESP_H
