# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_mrr_msgs/XCPMrrDtoReq.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class XCPMrrDtoReq(genpy.Message):
  _md5sum = "6c0c40e26206e4ff34d5667065aef2f1"
  _type = "delphi_mrr_msgs/XCPMrrDtoReq"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

uint8 mrrXcpDtoCmdByte7
uint8 mrrXcpDtoCmdByte6
uint8 mrrXcpDtoCmdByte5
uint8 mrrXcpDtoCmdByte4
uint8 mrrXcpDtoCmdByte3
uint8 mrrXcpDtoCmdByte2
uint8 mrrXcpDtoCmdByte1
uint8 mrrXcpDtoCmdByte0

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','mrrXcpDtoCmdByte7','mrrXcpDtoCmdByte6','mrrXcpDtoCmdByte5','mrrXcpDtoCmdByte4','mrrXcpDtoCmdByte3','mrrXcpDtoCmdByte2','mrrXcpDtoCmdByte1','mrrXcpDtoCmdByte0']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mrrXcpDtoCmdByte7,mrrXcpDtoCmdByte6,mrrXcpDtoCmdByte5,mrrXcpDtoCmdByte4,mrrXcpDtoCmdByte3,mrrXcpDtoCmdByte2,mrrXcpDtoCmdByte1,mrrXcpDtoCmdByte0

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XCPMrrDtoReq, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mrrXcpDtoCmdByte7 is None:
        self.mrrXcpDtoCmdByte7 = 0
      if self.mrrXcpDtoCmdByte6 is None:
        self.mrrXcpDtoCmdByte6 = 0
      if self.mrrXcpDtoCmdByte5 is None:
        self.mrrXcpDtoCmdByte5 = 0
      if self.mrrXcpDtoCmdByte4 is None:
        self.mrrXcpDtoCmdByte4 = 0
      if self.mrrXcpDtoCmdByte3 is None:
        self.mrrXcpDtoCmdByte3 = 0
      if self.mrrXcpDtoCmdByte2 is None:
        self.mrrXcpDtoCmdByte2 = 0
      if self.mrrXcpDtoCmdByte1 is None:
        self.mrrXcpDtoCmdByte1 = 0
      if self.mrrXcpDtoCmdByte0 is None:
        self.mrrXcpDtoCmdByte0 = 0
    else:
      self.header = std_msgs.msg.Header()
      self.mrrXcpDtoCmdByte7 = 0
      self.mrrXcpDtoCmdByte6 = 0
      self.mrrXcpDtoCmdByte5 = 0
      self.mrrXcpDtoCmdByte4 = 0
      self.mrrXcpDtoCmdByte3 = 0
      self.mrrXcpDtoCmdByte2 = 0
      self.mrrXcpDtoCmdByte1 = 0
      self.mrrXcpDtoCmdByte0 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.mrrXcpDtoCmdByte7, _x.mrrXcpDtoCmdByte6, _x.mrrXcpDtoCmdByte5, _x.mrrXcpDtoCmdByte4, _x.mrrXcpDtoCmdByte3, _x.mrrXcpDtoCmdByte2, _x.mrrXcpDtoCmdByte1, _x.mrrXcpDtoCmdByte0))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.mrrXcpDtoCmdByte7, _x.mrrXcpDtoCmdByte6, _x.mrrXcpDtoCmdByte5, _x.mrrXcpDtoCmdByte4, _x.mrrXcpDtoCmdByte3, _x.mrrXcpDtoCmdByte2, _x.mrrXcpDtoCmdByte1, _x.mrrXcpDtoCmdByte0,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.mrrXcpDtoCmdByte7, _x.mrrXcpDtoCmdByte6, _x.mrrXcpDtoCmdByte5, _x.mrrXcpDtoCmdByte4, _x.mrrXcpDtoCmdByte3, _x.mrrXcpDtoCmdByte2, _x.mrrXcpDtoCmdByte1, _x.mrrXcpDtoCmdByte0))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.mrrXcpDtoCmdByte7, _x.mrrXcpDtoCmdByte6, _x.mrrXcpDtoCmdByte5, _x.mrrXcpDtoCmdByte4, _x.mrrXcpDtoCmdByte3, _x.mrrXcpDtoCmdByte2, _x.mrrXcpDtoCmdByte1, _x.mrrXcpDtoCmdByte0,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
