# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from delphi_mrr_msgs/XCPMrrCtoResp.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class XCPMrrCtoResp(genpy.Message):
  _md5sum = "42b6d4ce0c3c9dd66c9872b88c9dcba3"
  _type = "delphi_mrr_msgs/XCPMrrCtoResp"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

uint8 mrrXcpCtoRespByte7
uint8 mrrXcpCtoRespByte6
uint8 mrrXcpCtoRespByte5
uint8 mrrXcpCtoRespByte4
uint8 mrrXcpCtoRespByte3
uint8 mrrXcpCtoRespByte2
uint8 mrrXcpCtoRespByte1
uint8 mrrXcpCtoRespByte0

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','mrrXcpCtoRespByte7','mrrXcpCtoRespByte6','mrrXcpCtoRespByte5','mrrXcpCtoRespByte4','mrrXcpCtoRespByte3','mrrXcpCtoRespByte2','mrrXcpCtoRespByte1','mrrXcpCtoRespByte0']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mrrXcpCtoRespByte7,mrrXcpCtoRespByte6,mrrXcpCtoRespByte5,mrrXcpCtoRespByte4,mrrXcpCtoRespByte3,mrrXcpCtoRespByte2,mrrXcpCtoRespByte1,mrrXcpCtoRespByte0

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XCPMrrCtoResp, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mrrXcpCtoRespByte7 is None:
        self.mrrXcpCtoRespByte7 = 0
      if self.mrrXcpCtoRespByte6 is None:
        self.mrrXcpCtoRespByte6 = 0
      if self.mrrXcpCtoRespByte5 is None:
        self.mrrXcpCtoRespByte5 = 0
      if self.mrrXcpCtoRespByte4 is None:
        self.mrrXcpCtoRespByte4 = 0
      if self.mrrXcpCtoRespByte3 is None:
        self.mrrXcpCtoRespByte3 = 0
      if self.mrrXcpCtoRespByte2 is None:
        self.mrrXcpCtoRespByte2 = 0
      if self.mrrXcpCtoRespByte1 is None:
        self.mrrXcpCtoRespByte1 = 0
      if self.mrrXcpCtoRespByte0 is None:
        self.mrrXcpCtoRespByte0 = 0
    else:
      self.header = std_msgs.msg.Header()
      self.mrrXcpCtoRespByte7 = 0
      self.mrrXcpCtoRespByte6 = 0
      self.mrrXcpCtoRespByte5 = 0
      self.mrrXcpCtoRespByte4 = 0
      self.mrrXcpCtoRespByte3 = 0
      self.mrrXcpCtoRespByte2 = 0
      self.mrrXcpCtoRespByte1 = 0
      self.mrrXcpCtoRespByte0 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.mrrXcpCtoRespByte7, _x.mrrXcpCtoRespByte6, _x.mrrXcpCtoRespByte5, _x.mrrXcpCtoRespByte4, _x.mrrXcpCtoRespByte3, _x.mrrXcpCtoRespByte2, _x.mrrXcpCtoRespByte1, _x.mrrXcpCtoRespByte0))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.mrrXcpCtoRespByte7, _x.mrrXcpCtoRespByte6, _x.mrrXcpCtoRespByte5, _x.mrrXcpCtoRespByte4, _x.mrrXcpCtoRespByte3, _x.mrrXcpCtoRespByte2, _x.mrrXcpCtoRespByte1, _x.mrrXcpCtoRespByte0,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.mrrXcpCtoRespByte7, _x.mrrXcpCtoRespByte6, _x.mrrXcpCtoRespByte5, _x.mrrXcpCtoRespByte4, _x.mrrXcpCtoRespByte3, _x.mrrXcpCtoRespByte2, _x.mrrXcpCtoRespByte1, _x.mrrXcpCtoRespByte0))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.mrrXcpCtoRespByte7, _x.mrrXcpCtoRespByte6, _x.mrrXcpCtoRespByte5, _x.mrrXcpCtoRespByte4, _x.mrrXcpCtoRespByte3, _x.mrrXcpCtoRespByte2, _x.mrrXcpCtoRespByte1, _x.mrrXcpCtoRespByte0,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
